// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef _FINDMYGROCERY_UI_H
#define _FINDMYGROCERY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_screenLoader.h"
#include "screens/ui_screenHome.h"
#include "screens/ui_screenFindBook.h"
#include "screens/ui_screenFindBookInfo.h"
#include "screens/ui_screenIssueScan.h"
#include "screens/ui_screenIssueEnrollment.h"
#include "screens/ui_screenIssueFinalConfirm.h"
#include "screens/ui_screenIssueOtp.h"
#include "screens/ui_screenIssueOtpSuccess.h"
#include "screens/ui_screenIssueOtpFail.h"
#include "screens/ui_screenReturnScan.h"
#include "screens/ui_screenReturnSuccess.h"
#include "screens/ui_screenAbout.h"
#include "screens/ui_ScreenFindAGrocery.h"
#include "screens/ui_ScreenFindVoice.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * LoadingAnimationLogo_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LoadingAnimationText_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Opacity1_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_fmg_logo_png);    // assets/FMG Logo.png
LV_IMG_DECLARE(ui_img_fmg_text_png);    // assets/FMG Text.png
LV_IMG_DECLARE(ui_img_find_a_grocery_png);    // assets/find a grocery.png
LV_IMG_DECLARE(ui_img_knowprice_png);    // assets/knowprice.png
LV_IMG_DECLARE(ui_img_check_price_png);    // assets/check price.png
LV_IMG_DECLARE(ui_img_makeorder_png);    // assets/makeorder.png
LV_IMG_DECLARE(ui_img_backbtn_png);    // assets/backBtn.png
LV_IMG_DECLARE(ui_img_backpressed_png);    // assets/backpressed.png
LV_IMG_DECLARE(ui_img_cross_png);    // assets/cross.png
LV_IMG_DECLARE(ui_img_issue_book_icon_png);    // assets/issue book icon.png
LV_IMG_DECLARE(ui_img_rfidicon_png);    // assets/RFIDicon.png
LV_IMG_DECLARE(ui_img_success_png);    // assets/success.png
LV_IMG_DECLARE(ui_img_failed_png);    // assets/Failed.png
LV_IMG_DECLARE(ui_img_return_book_icon_png);    // assets/return book icon.png
LV_IMG_DECLARE(ui_img_about_us_icon_png);    // assets/About Us icon.png
LV_IMG_DECLARE(ui_img_typesearch_png);    // assets/TypeSearch.png
LV_IMG_DECLARE(ui_img_voicesearch_png);    // assets/voicesearch.png
LV_IMG_DECLARE(ui_img_speakvs_png);    // assets/SpeakVS.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
