// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Smart_LIbrary_Management

#ifndef UI_SCREENISSUEOTPFAIL_H
#define UI_SCREENISSUEOTPFAIL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenIssueOtpFail
extern void ui_screenIssueOtpFail_screen_init(void);
extern void ui_screenIssueOtpFail_screen_destroy(void);
extern lv_obj_t * ui_screenIssueOtpFail;
extern void ui_event_btnissuegoback(lv_event_t * e);
extern lv_obj_t * ui_btnissuegoback;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

