// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Smart_LIbrary_Management

#include "../ui.h"
#include "keyboard.h"
#include "esp_log.h"
#include "issue_state.h"
#include "api_issueBook.h"
lv_obj_t * ui_screenIssueEnrollment = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_ImgButton9 = NULL;
lv_obj_t * ui_taEnrollmentNum = NULL;
lv_obj_t * ui_btnCheckUser = NULL;
lv_obj_t * ui_Label23 = NULL;
// event funtions
void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenIssueScan, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenIssueScan_screen_init);
    }
}

void ui_event_btnCheckUser(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;

    const char *enroll = lv_textarea_get_text(ui_taEnrollmentNum);

    if(strlen(enroll) == 0) return;

    strncpy(g_issue_session.enrollment_no, enroll, sizeof(g_issue_session.enrollment_no)-1);

    start_issue_fetch_task();
}

void ui_event_taEnrollmentNum(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if(code == LV_EVENT_FOCUSED) {
        ESP_LOGI("TA", "Enrollment textarea focused → show keyboard");

        // Ensure keyboard is created on the **current screen**
        // This makes sure parenting is correct (avoids invisible keyboard).
        keyboard_create(NULL);   // NULL -> use lv_scr_act() inside function
        lv_keyboard_set_mode(ui_keyboard, LV_KEYBOARD_MODE_NUMBER);

        // Link keyboard and textarea, show, bring to front
        lv_keyboard_set_textarea(ui_keyboard, ui_taEnrollmentNum);
        lv_obj_clear_flag(ui_keyboard, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(ui_keyboard);
        ESP_LOGI("TA","keyboard parent=%p visible? %d", lv_obj_get_parent(ui_keyboard), !lv_obj_has_flag(ui_keyboard, LV_OBJ_FLAG_HIDDEN));

    }

    if(code == LV_EVENT_DEFOCUSED || code == LV_EVENT_READY) {
        ESP_LOGI("TA", "Enrollment textarea defocused → hide keyboard");
        keyboard_hide();
    }
}
// build funtions

void ui_screenIssueEnrollment_screen_init(void)
{
    ui_screenIssueEnrollment = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenIssueEnrollment, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenIssueEnrollment, lv_color_hex(0xFBBF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenIssueEnrollment, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenIssueEnrollment, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenIssueEnrollment, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_screenIssueEnrollment);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, -48);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Enter Enrollment Number");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x010045), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_screenIssueEnrollment);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 10);
    lv_obj_set_y(ui_Label26, -92);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "User Verification");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton9 = lv_imgbtn_create(ui_screenIssueEnrollment);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton9, 30);
    lv_obj_set_height(ui_ImgButton9, 30);
    lv_obj_set_x(ui_ImgButton9, -134);
    lv_obj_set_y(ui_ImgButton9, -91);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);

    ui_taEnrollmentNum = lv_textarea_create(ui_screenIssueEnrollment);
    lv_obj_set_width(ui_taEnrollmentNum, 256);
    lv_obj_set_height(ui_taEnrollmentNum, 40);
    lv_obj_set_x(ui_taEnrollmentNum, 0);
    lv_obj_set_y(ui_taEnrollmentNum, 5);
    lv_obj_set_align(ui_taEnrollmentNum, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_taEnrollmentNum, "Enter Enrollment Number");
    lv_obj_set_style_text_color(ui_taEnrollmentNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taEnrollmentNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taEnrollmentNum, lv_color_hex(0xCCC6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taEnrollmentNum, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_taEnrollmentNum, lv_color_hex(0xC6C1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_taEnrollmentNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_taEnrollmentNum, lv_color_hex(0x000000),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taEnrollmentNum, 180, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_taEnrollmentNum, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_taEnrollmentNum, LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_obj_add_event_cb(ui_taEnrollmentNum, ui_event_taEnrollmentNum, LV_EVENT_ALL, NULL);

    ui_btnCheckUser = lv_btn_create(ui_screenIssueEnrollment);
    lv_obj_set_width(ui_btnCheckUser, 256);
    lv_obj_set_height(ui_btnCheckUser, 40);
    lv_obj_set_x(ui_btnCheckUser, 0);
    lv_obj_set_y(ui_btnCheckUser, 62);
    lv_obj_set_align(ui_btnCheckUser, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCheckUser, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCheckUser, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnCheckUser, lv_color_hex(0x00025A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnCheckUser, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnCheckUser, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnCheckUser, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnCheckUser, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnCheckUser, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnCheckUser, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnCheckUser, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnCheckUser, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnCheckUser, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnCheckUser, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnCheckUser, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_btnCheckUser, ui_event_btnCheckUser, LV_EVENT_ALL, NULL);

    ui_Label23 = lv_label_create(ui_btnCheckUser);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Check User");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton9, ui_event_ImgButton9, LV_EVENT_ALL, NULL);
    keyboard_create(ui_screenIssueEnrollment);

}

void ui_screenIssueEnrollment_screen_destroy(void)
{
    keyboard_hide();

    if(ui_screenIssueEnrollment) lv_obj_del(ui_screenIssueEnrollment);

    // NULL screen variables
    ui_screenIssueEnrollment = NULL;
    ui_Label22 = NULL;
    ui_Label26 = NULL;
    ui_ImgButton9 = NULL;
    ui_taEnrollmentNum = NULL;
    ui_btnCheckUser = NULL;
    ui_Label23 = NULL;

}
