// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Smart_LIbrary_Management

#ifndef UI_SCREENISSUEOTP_H
#define UI_SCREENISSUEOTP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenIssueOtp
extern void ui_screenIssueOtp_screen_init(void);
extern void ui_screenIssueOtp_screen_destroy(void);
extern lv_obj_t * ui_screenIssueOtp;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_labelUVName;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label24;
extern void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
extern lv_obj_t * ui_taOtpInput;
extern lv_obj_t * ui_btnSubmitOtp;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_labelUVMaskedEmail;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

