// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Smart_LIbrary_Management

#ifndef UI_SCREENRETURNSCAN_H
#define UI_SCREENRETURNSCAN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenReturnScan
extern void ui_screenReturnScan_screen_init(void);
extern void ui_screenReturnScan_screen_destroy(void);
extern lv_obj_t * ui_screenReturnScan;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label36;
extern void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label42;
extern void ui_event_btnCancelReturn(lv_event_t * e);
extern lv_obj_t * ui_btnCancelReturn;
extern lv_obj_t * ui_Label43;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

