// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Smart_LIbrary_Management

#include "../ui.h"
#include "issue_state.h"
#include <string.h>
#include "keyboard.h"
#include "esp_log.h"
#include <stdio.h>
#include "api_issueOtp.h"
#include "api_issueDone.h"
lv_obj_t * ui_screenIssueOtp = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_labelUVName = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_ImgButton8 = NULL;
lv_obj_t * ui_taOtpInput = NULL;
lv_obj_t * ui_btnSubmitOtp = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_labelUVMaskedEmail = NULL;
// event funtions
static void mask_email(const char *email, char *out, size_t out_size)
{
    const char *at = strchr(email, '@');
    if (!at) {
        strncpy(out, "***", out_size);
        return;
    }

    int name_len = at - email;

    if (name_len <= 5) {
        // Too short → simple mask
        snprintf(out, out_size, "%.*s****%s", name_len > 2 ? 2 : name_len, email, at);
        return;
    }

    const char *last2 = at - 2;

    snprintf(out, out_size,
             "%.*s****%.*s%s",
             3, email,          // first 3
             2, last2,          // last 2 before @
             at);               // domain
}

static void ui_event_screenIssueOtp(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_SCREEN_LOAD_START) return;
    lv_textarea_set_text(ui_taOtpInput, "");
    lv_label_set_text(ui_labelUVName, g_issue_session.user_name);

    char masked_email[64];
    mask_email(g_issue_session.email, masked_email, sizeof(masked_email));
    lv_label_set_text(ui_labelUVMaskedEmail, masked_email);
    start_issue_otp_request_task();  
}

void ui_event_taOtpInput(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if(code == LV_EVENT_FOCUSED) {
        ESP_LOGI("TA", "OTP textarea focused → show keyboard");

        // Ensure keyboard is created on the **current screen**
        // This makes sure parenting is correct (avoids invisible keyboard).
        keyboard_create(NULL);   // NULL -> use lv_scr_act() inside function
        lv_keyboard_set_mode(ui_keyboard, LV_KEYBOARD_MODE_NUMBER);

        // Link keyboard and textarea, show, bring to front
        lv_keyboard_set_textarea(ui_keyboard, ui_taOtpInput);
        lv_obj_clear_flag(ui_keyboard, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(ui_keyboard);
        ESP_LOGI("TA","keyboard parent=%p visible? %d", lv_obj_get_parent(ui_keyboard), !lv_obj_has_flag(ui_keyboard, LV_OBJ_FLAG_HIDDEN));

    }

    if(code == LV_EVENT_DEFOCUSED || code == LV_EVENT_READY) {
        ESP_LOGI("TA", "OTP textarea defocused → hide keyboard");
        keyboard_hide();
    }
}

void ui_event_btnSubmitOtp(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;

    const char *entered = lv_textarea_get_text(ui_taOtpInput);

    if(strcmp(entered, g_issue_session.otp) == 0)
    {
        start_issue_commit_task();
        _ui_screen_change(&ui_screenIssueOtpSuccess, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0,
                          &ui_screenIssueOtpSuccess_screen_init);
    }
    else
    {
        _ui_screen_change(&ui_screenIssueOtpFail, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0,
                          &ui_screenIssueOtpFail_screen_init);
    }
}

void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenIssueEnrollment, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenIssueEnrollment_screen_init);
    }
}

// build funtions

void ui_screenIssueOtp_screen_init(void)
{
    ui_screenIssueOtp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenIssueOtp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenIssueOtp, lv_color_hex(0xFBBF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenIssueOtp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenIssueOtp, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenIssueOtp, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_screenIssueOtp);
    lv_obj_set_width(ui_Label20, 213);
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -35);
    lv_obj_set_y(ui_Label20, -53);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Hello");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x010045), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUVName = lv_label_create(ui_screenIssueOtp);
    lv_obj_set_width(ui_labelUVName, 213);
    lv_obj_set_height(ui_labelUVName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelUVName, 11);
    lv_obj_set_y(ui_labelUVName, -53);
    lv_obj_set_align(ui_labelUVName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUVName, "Name Here");
    lv_obj_set_style_text_color(ui_labelUVName, lv_color_hex(0x010045), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUVName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUVName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_screenIssueOtp);
    lv_obj_set_width(ui_Label27, 180);
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -52);
    lv_obj_set_y(ui_Label27, -32);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Enter the OTP sent on : ");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x010045), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_screenIssueOtp);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 5);
    lv_obj_set_y(ui_Label24, -92);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "User Verification");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton8 = lv_imgbtn_create(ui_screenIssueOtp);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton8, 30);
    lv_obj_set_height(ui_ImgButton8, 30);
    lv_obj_set_x(ui_ImgButton8, -139);
    lv_obj_set_y(ui_ImgButton8, -91);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

    ui_taOtpInput = lv_textarea_create(ui_screenIssueOtp);
    lv_obj_set_width(ui_taOtpInput, 256);
    lv_obj_set_height(ui_taOtpInput, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_taOtpInput, 0);
    lv_obj_set_y(ui_taOtpInput, 5);
    lv_obj_set_align(ui_taOtpInput, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_taOtpInput, "1234567890");
    lv_textarea_set_max_length(ui_taOtpInput, 6);
    lv_textarea_set_placeholder_text(ui_taOtpInput, "000000");
    lv_textarea_set_one_line(ui_taOtpInput, true);
    lv_obj_set_style_text_color(ui_taOtpInput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taOtpInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_taOtpInput, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_taOtpInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taOtpInput, lv_color_hex(0xCCC6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taOtpInput, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_taOtpInput, lv_color_hex(0xC6C1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_taOtpInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_taOtpInput, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taOtpInput, 180, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_taOtpInput, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_taOtpInput, ui_event_taOtpInput, LV_EVENT_ALL, NULL);

    ui_btnSubmitOtp = lv_btn_create(ui_screenIssueOtp);
    lv_obj_set_width(ui_btnSubmitOtp, 256);
    lv_obj_set_height(ui_btnSubmitOtp, 40);
    lv_obj_set_x(ui_btnSubmitOtp, 0);
    lv_obj_set_y(ui_btnSubmitOtp, 62);
    lv_obj_set_align(ui_btnSubmitOtp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSubmitOtp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSubmitOtp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSubmitOtp, lv_color_hex(0x00025A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSubmitOtp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnSubmitOtp, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnSubmitOtp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnSubmitOtp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnSubmitOtp, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSubmitOtp, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSubmitOtp, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSubmitOtp, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSubmitOtp, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnSubmitOtp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnSubmitOtp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_btnSubmitOtp, ui_event_btnSubmitOtp, LV_EVENT_ALL, NULL);

    ui_Label25 = lv_label_create(ui_btnSubmitOtp);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Submit");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUVMaskedEmail = lv_label_create(ui_screenIssueOtp);
    lv_obj_set_width(ui_labelUVMaskedEmail, 180);
    lv_obj_set_height(ui_labelUVMaskedEmail, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelUVMaskedEmail, 92);
    lv_obj_set_y(ui_labelUVMaskedEmail, -32);
    lv_obj_set_align(ui_labelUVMaskedEmail, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUVMaskedEmail, "");
    lv_obj_set_style_text_color(ui_labelUVMaskedEmail, lv_color_hex(0x010045), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUVMaskedEmail, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUVMaskedEmail, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenIssueOtp,
                    ui_event_screenIssueOtp,
                    LV_EVENT_ALL,
                    NULL);
    keyboard_create(ui_screenIssueOtp);

}

void ui_screenIssueOtp_screen_destroy(void)
{
    keyboard_hide();
    if(ui_screenIssueOtp) lv_obj_del(ui_screenIssueOtp);

    // NULL screen variables
    ui_screenIssueOtp = NULL;
    ui_Label20 = NULL;
    ui_labelUVName = NULL;
    ui_Label27 = NULL;
    ui_Label24 = NULL;
    ui_ImgButton8 = NULL;
    ui_taOtpInput = NULL;
    ui_btnSubmitOtp = NULL;
    ui_Label25 = NULL;
    ui_labelUVMaskedEmail = NULL;

}
