// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Smart_LIbrary_Management

#include "../ui.h"
#include "esp_log.h"  
#include "findbook_task.h"
#include <stdio.h>
#include "keyboard.h"

lv_obj_t * ui_screenFindBook = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_taFBookName = NULL;
lv_obj_t * ui_btnSearchBook = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_btnMic = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
lv_obj_t * ui_ErrorFBEBN = NULL;

// event funtions
void ui_event_screenFindBook(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_opacity_set(ui_ErrorFBEBN, 0);
    }
}

static void go_to_findbook_info(void *arg)
{
    /* Set data on next screen */
    lv_label_set_text(ui_labelBDBookName, g_findbook_name);

    char location[64];
    snprintf(location, sizeof(location),
             "Rack %s  %s Side Row %d  Col %d",
             g_findbook_rack,
             g_findbook_side,
             g_findbook_row,
             g_findbook_column);

    lv_label_set_text(ui_labelBDLocation, location);

    /* NOW change screen (SAFE PLACE) */
    _ui_screen_change(
        &ui_screenFindBookInfo,
        LV_SCR_LOAD_ANIM_FADE_ON,
        300,
        0,
        &ui_screenFindBookInfo_screen_init
    );
}

void ui_event_btnSearchBook(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;

    const char *book_name = lv_textarea_get_text(ui_taFBookName);
    if (!book_name || strlen(book_name) == 0) return;

    ESP_LOGI("SEARCH", "Starting find book task");
    start_findbook_task(book_name);   
}
// void ui_event_btnSearchBook(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_screenFindBookInfo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenFindBookInfo_screen_init);
//     }
// }

void ui_event_taFBookName(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    // ESP_LOGI("TA", "Textarea event: %d", code);

    if(code == LV_EVENT_FOCUSED) {
        ESP_LOGI("TA", "Textarea focused → show keyboard");
        keyboard_create(NULL);
        lv_keyboard_set_textarea(ui_keyboard, ui_taFBookName);
        lv_obj_clear_flag(ui_keyboard, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(ui_keyboard);
        ESP_LOGI("TA","keyboard parent=%p visible? %d", lv_obj_get_parent(ui_keyboard), !lv_obj_has_flag(ui_keyboard, LV_OBJ_FLAG_HIDDEN));

    }

    if(code == LV_EVENT_DEFOCUSED || code == LV_EVENT_READY) {
        ESP_LOGI("TA", "Textarea defocused → hide keyboard");
        keyboard_hide();
    }
    if (code == LV_EVENT_VALUE_CHANGED) {
        lv_obj_set_style_opa(ui_ErrorFBEBN, 0, LV_PART_MAIN);
    }

}


void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_screenFindBook_screen_init(void)
{
    ui_screenFindBook = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenFindBook, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenFindBook, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenFindBook, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenFindBook, lv_color_hex(0x3DB0E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenFindBook, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_screenFindBook);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 317);
    lv_obj_set_height(ui_Container5, 50);
    lv_obj_set_x(ui_Container5, 5);
    lv_obj_set_y(ui_Container5, -85);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Container5);
    lv_img_set_src(ui_Image13, &ui_img_find_book_icon_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image13, -81);
    lv_obj_set_y(ui_Image13, 0);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 36);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Find Book");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_screenFindBook);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -1);
    lv_obj_set_y(ui_Label9, -36);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Enter Book Name");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taFBookName = lv_textarea_create(ui_screenFindBook);
    lv_obj_set_width(ui_taFBookName, 256);
    lv_obj_set_height(ui_taFBookName, 40);
    lv_obj_set_x(ui_taFBookName, 0);
    lv_obj_set_y(ui_taFBookName, 5);
    lv_obj_set_align(ui_taFBookName, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_taFBookName, "Enter Book Name");
    lv_obj_set_style_text_color(ui_taFBookName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taFBookName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taFBookName, lv_color_hex(0xCCC6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taFBookName, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_taFBookName, lv_color_hex(0xC6C1E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_taFBookName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_taFBookName, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taFBookName, 180, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_taFBookName, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_taFBookName, LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_obj_add_event_cb(ui_taFBookName, ui_event_taFBookName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(
        ui_taFBookName,
        ui_event_taFBookName,
        LV_EVENT_ALL,
        NULL
    );

    ui_btnSearchBook = lv_btn_create(ui_screenFindBook);
    lv_obj_set_width(ui_btnSearchBook, 256);
    lv_obj_set_height(ui_btnSearchBook, 40);
    lv_obj_set_x(ui_btnSearchBook, 0);
    lv_obj_set_y(ui_btnSearchBook, 67);
    lv_obj_set_align(ui_btnSearchBook, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSearchBook, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSearchBook, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSearchBook, lv_color_hex(0x00025A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSearchBook, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnSearchBook, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnSearchBook, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnSearchBook, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnSearchBook, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSearchBook, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSearchBook, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSearchBook, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSearchBook, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnSearchBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnSearchBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_btnSearchBook);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Search");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnMic = lv_imgbtn_create(ui_screenFindBook);
    lv_imgbtn_set_src(ui_btnMic, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mic_png, NULL);
    lv_imgbtn_set_src(ui_btnMic, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_mic_png, NULL);
    lv_obj_set_width(ui_btnMic, 40);
    lv_obj_set_height(ui_btnMic, 41);
    lv_obj_set_x(ui_btnMic, 115);
    lv_obj_set_y(ui_btnMic, 11);
    lv_obj_set_align(ui_btnMic, LV_ALIGN_CENTER);
    lv_obj_set_style_transform_zoom(ui_btnMic, 170, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton6 = lv_imgbtn_create(ui_screenFindBook);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton6, 30);
    lv_obj_set_height(ui_ImgButton6, 30);
    lv_obj_set_x(ui_ImgButton6, -134);
    lv_obj_set_y(ui_ImgButton6, -85);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_ErrorFBEBN = lv_label_create(ui_screenFindBook);
    lv_obj_set_width(ui_ErrorFBEBN, 247);
    lv_obj_set_height(ui_ErrorFBEBN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ErrorFBEBN, -1);
    lv_obj_set_y(ui_ErrorFBEBN, 35);
    lv_obj_set_align(ui_ErrorFBEBN, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_ErrorFBEBN, "Book Not Found, Try another book.");
    lv_obj_set_style_text_color(ui_ErrorFBEBN, lv_color_hex(0xC90F39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ErrorFBEBN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ErrorFBEBN, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ErrorFBEBN, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ErrorFBEBN, 0, LV_PART_MAIN);
    lv_label_set_text(ui_ErrorFBEBN, "");


    lv_obj_add_event_cb(ui_btnSearchBook, ui_event_btnSearchBook, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenFindBook, ui_event_screenFindBook, LV_EVENT_ALL, NULL);

    // keyboard_init();   
    keyboard_create(ui_screenFindBook);
    // ESP_LOGI("Keyboard initialized successfully");

}

void ui_screenFindBook_screen_destroy(void)
{
    keyboard_hide();
    if(ui_screenFindBook) lv_obj_del(ui_screenFindBook);

    // NULL screen variables
    ui_screenFindBook = NULL;
    ui_Container5 = NULL;
    ui_Image13 = NULL;
    ui_Label6 = NULL;
    ui_Label9 = NULL;
    ui_taFBookName = NULL;
    ui_btnSearchBook = NULL;
    ui_Label10 = NULL;
    ui_btnMic = NULL;
    ui_ImgButton6 = NULL;
    ui_ErrorFBEBN = NULL;

}
