idf_component_register(
    SRCS
        screens/ui_screenLoader.c
        screens/ui_screenHome.c
        screens/ui_screenFindBook.c
        screens/ui_screenFindBookInfo.c
        screens/ui_screenIssueScan.c
        screens/ui_screenIssueEnrollment.c
        screens/ui_screenIssueFinalConfirm.c
        screens/ui_screenIssueOtp.c
        screens/ui_screenIssueOtpSuccess.c
        screens/ui_screenIssueOtpFail.c
        screens/ui_screenReturnScan.c
        screens/ui_screenReturnSuccess.c
        screens/ui_screenAbout.c
        screens/blink_task.c
        screens/ui_screenPriceOfProduct.c
        screens/ui_screenProductDetails.c
        screens/ui_screenCreateBill.c
        screens/ui_ScreenBillCreatedSuccess.c
        screens/ui_ScreenFindAGrocery.c
        screens/ui_ScreenFindVoice.c
        rfid/rfid_service.c
        rfid/rfid_handler.c
        rfid/rfid_state.c
        rfid/issue_state.c
        rfid/returnHandler.c
        ui.c
        ui_helpers.c
        keyboard.c
        api_findbook.c
        api_blinkbook.c
        api_issueBook.c
        findbook_task.c
        api_issueOtp.c
        api_issueDone.c
        api_returnBook.c
        api_blinkRack.c
        http_server.c
        qr_mapper.c
        theft_handler.c
        api_theft_check.c
        ui_screenVoiceOverlay.c
        components/ui_comp_hook.c
        images/ui_img_fmg_logo_png.c
        images/ui_img_fmg_text_png.c
        images/ui_img_find_a_grocery_png.c
        images/ui_img_knowprice_png.c
        images/ui_img_check_price_png.c
        images/ui_img_makeorder_png.c
        images/ui_img_return_book_icon_png.c
        images/ui_img_rfidorcam_png.c
        images/ui_img_rfidicon_png.c
        images/ui_img_about_us_icon_png.c
        images/ui_img_backbtn_png.c
        images/ui_img_backpressed_png.c
        images/ui_img_cross_png.c
        images/ui_img_rfidicon_png.c
        images/ui_img_success_png.c
        images/ui_img_failed_png.c
        images/ui_img_map_a_right_png.c
        images/ui_img_map_a_left_png.c
        images/ui_img_map_b_left_png.c
        images/ui_img_map_b_right_png.c
        images/ui_img_qr_ar1c1l_png.c
        images/ui_img_qr_ar1c1r_png.c
        images/ui_img_qr_ar1c2l_png.c
        images/ui_img_qr_ar1c2r_png.c
        images/ui_img_qr_ar2c1l_png.c
        images/ui_img_qr_ar2c1r_png.c
        images/ui_img_qr_ar2c2l_png.c
        images/ui_img_qr_ar2c2r_png.c
        images/ui_img_qr_br1c1l_png.c
        images/ui_img_qr_br1c1r_png.c
        images/ui_img_qr_br1c2l_png.c
        images/ui_img_qr_br1c2r_png.c
        images/ui_img_qr_br2c1l_png.c
        images/ui_img_qr_br2c1r_png.c
        images/ui_img_qr_br2c2l_png.c
        images/ui_img_qr_br2c2r_png.c
        images/ui_img_typesearch_png.c
        images/ui_img_voicesearch_png.c
        images/ui_img_speakvs_png.c
        images/ui_img_pdcam_png.c
        images/ui_img_billcreatedsuccess_png.c        
    SRC_DIRS
        "."
        "screens"
        "../wifi"
    INCLUDE_DIRS
        "." 
        "include"  
    REQUIRES
        lvgl__lvgl
        esp_http_client
        cjson
        esp_http_server
    PRIV_REQUIRES esp_driver_uart 

)
