// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_screenIssueOtpFail = NULL;
lv_obj_t * ui_btnissuegoback = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Label34 = NULL;
// event funtions
void ui_event_btnissuegoback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenIssueScan, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenIssueScan_screen_init);
    }
}

// build funtions

void ui_screenIssueOtpFail_screen_init(void)
{
    ui_screenIssueOtpFail = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenIssueOtpFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenIssueOtpFail, lv_color_hex(0xFBBF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenIssueOtpFail, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenIssueOtpFail, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenIssueOtpFail, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnissuegoback = lv_btn_create(ui_screenIssueOtpFail);
    lv_obj_set_width(ui_btnissuegoback, 256);
    lv_obj_set_height(ui_btnissuegoback, 40);
    lv_obj_set_x(ui_btnissuegoback, 0);
    lv_obj_set_y(ui_btnissuegoback, 62);
    lv_obj_set_align(ui_btnissuegoback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnissuegoback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnissuegoback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnissuegoback, lv_color_hex(0x00025A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnissuegoback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnissuegoback, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnissuegoback, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnissuegoback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnissuegoback, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnissuegoback, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnissuegoback, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnissuegoback, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnissuegoback, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnissuegoback, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnissuegoback, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_btnissuegoback);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Go Back");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_screenIssueOtpFail);
    lv_img_set_src(ui_Image8, &ui_img_failed_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, -65);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_screenIssueOtpFail);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 0);
    lv_obj_set_y(ui_Label33, -3);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Book Issue Failed");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_screenIssueOtpFail);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 0);
    lv_obj_set_y(ui_Label34, 16);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "You entered an Incorrect OTP");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnissuegoback, ui_event_btnissuegoback, LV_EVENT_ALL, NULL);

}

void ui_screenIssueOtpFail_screen_destroy(void)
{
    if(ui_screenIssueOtpFail) lv_obj_del(ui_screenIssueOtpFail);

    // NULL screen variables
    ui_screenIssueOtpFail = NULL;
    ui_btnissuegoback = NULL;
    ui_Label31 = NULL;
    ui_Image8 = NULL;
    ui_Label33 = NULL;
    ui_Label34 = NULL;

}
