// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENPRODUCTDETAILS_H
#define UI_SCREENPRODUCTDETAILS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenProductDetails
extern void ui_screenProductDetails_screen_init(void);
extern void ui_screenProductDetails_screen_destroy(void);
extern lv_obj_t * ui_screenProductDetails;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_LabelWIS;
extern void ui_event_ImgButton17(lv_event_t * e);
extern lv_obj_t * ui_ImgButton17;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

