// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenHome
extern void ui_screenHome_screen_init(void);
extern void ui_screenHome_screen_destroy(void);
extern void ui_event_screenHome(lv_event_t * e);
extern lv_obj_t * ui_screenHome;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Container2;
extern void ui_event_btnFindBook(lv_event_t * e);
extern lv_obj_t * ui_btnFindBook;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label2;
extern void ui_event_btnReturnBook(lv_event_t * e);
extern lv_obj_t * ui_btnReturnBook;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image9;
extern void ui_event_btnIssueBook(lv_event_t * e);
extern lv_obj_t * ui_btnIssueBook;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label4;
extern void ui_event_btnAboutUs(lv_event_t * e);
extern lv_obj_t * ui_btnAboutUs;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

