// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_screenReturnSuccess = NULL;
lv_obj_t * ui_btnReturnDone = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_Label38 = NULL;
// event funtions
void ui_event_btnReturnDone(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_screenReturnSuccess_screen_init(void)
{
    ui_screenReturnSuccess = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenReturnSuccess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenReturnSuccess, lv_color_hex(0x16A34A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenReturnSuccess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenReturnSuccess, lv_color_hex(0x4ADE80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenReturnSuccess, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnReturnDone = lv_btn_create(ui_screenReturnSuccess);
    lv_obj_set_width(ui_btnReturnDone, 256);
    lv_obj_set_height(ui_btnReturnDone, 40);
    lv_obj_set_x(ui_btnReturnDone, 0);
    lv_obj_set_y(ui_btnReturnDone, 62);
    lv_obj_set_align(ui_btnReturnDone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnReturnDone, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnReturnDone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnReturnDone, lv_color_hex(0x00025A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnReturnDone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnReturnDone, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnReturnDone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnReturnDone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnReturnDone, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnReturnDone, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnReturnDone, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnReturnDone, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnReturnDone, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnReturnDone, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnReturnDone, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_btnReturnDone);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Done");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_screenReturnSuccess);
    lv_img_set_src(ui_Image12, &ui_img_success_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, -65);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_screenReturnSuccess);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 0);
    lv_obj_set_y(ui_Label37, -3);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Book Returned Successfully");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_screenReturnSuccess);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 0);
    lv_obj_set_y(ui_Label38, 16);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "Confirmation email sent!");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnReturnDone, ui_event_btnReturnDone, LV_EVENT_ALL, NULL);

}

void ui_screenReturnSuccess_screen_destroy(void)
{
    if(ui_screenReturnSuccess) lv_obj_del(ui_screenReturnSuccess);

    // NULL screen variables
    ui_screenReturnSuccess = NULL;
    ui_btnReturnDone = NULL;
    ui_Label35 = NULL;
    ui_Image12 = NULL;
    ui_Label37 = NULL;
    ui_Label38 = NULL;

}
