// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENFINDAGROCERY_H
#define UI_SCREENFINDAGROCERY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenFindAGrocery
extern void ui_ScreenFindAGrocery_screen_init(void);
extern void ui_ScreenFindAGrocery_screen_destroy(void);
extern lv_obj_t * ui_ScreenFindAGrocery;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label52;
extern void ui_event_ImgButton12(lv_event_t * e);
extern lv_obj_t * ui_ImgButton12;
extern lv_obj_t * ui_Label16;
extern void ui_event_btnTypeSearch(lv_event_t * e);
extern lv_obj_t * ui_btnTypeSearch;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Label55;
extern void ui_event_btnVoiceSearch(lv_event_t * e);
extern lv_obj_t * ui_btnVoiceSearch;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Label58;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

