// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_screenReturnScan = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_ImgButton10 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_btnCancelReturn = NULL;
lv_obj_t * ui_Label43 = NULL;
// event funtions
void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

void ui_event_btnCancelReturn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_screenReturnScan_screen_init(void)
{
    ui_screenReturnScan = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenReturnScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenReturnScan, lv_color_hex(0x16A34A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenReturnScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenReturnScan, lv_color_hex(0x4ADE80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenReturnScan, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_screenReturnScan);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 312);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, -85);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Container4);
    lv_img_set_src(ui_Image14, &ui_img_return_book_icon_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image14, -81);
    lv_obj_set_y(ui_Image14, 0);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 36);
    lv_obj_set_y(ui_Label36, 0);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Return Book");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton10 = lv_imgbtn_create(ui_screenReturnScan);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton10, 30);
    lv_obj_set_height(ui_ImgButton10, 30);
    lv_obj_set_x(ui_ImgButton10, -134);
    lv_obj_set_y(ui_ImgButton10, -85);
    lv_obj_set_align(ui_ImgButton10, LV_ALIGN_CENTER);

    ui_Label41 = lv_label_create(ui_screenReturnScan);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 0);
    lv_obj_set_y(ui_Label41, -48);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Please scan book RFID");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x010045), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_img_create(ui_screenReturnScan);
    lv_img_set_src(ui_Image18, &ui_img_rfidicon_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 112
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 58
    lv_obj_set_x(ui_Image18, 0);
    lv_obj_set_y(ui_Image18, 3);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label42 = lv_label_create(ui_screenReturnScan);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, 0);
    lv_obj_set_y(ui_Label42, 43);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "Waiting for RFID....");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0x125400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCancelReturn = lv_btn_create(ui_screenReturnScan);
    lv_obj_set_width(ui_btnCancelReturn, 256);
    lv_obj_set_height(ui_btnCancelReturn, 40);
    lv_obj_set_x(ui_btnCancelReturn, 0);
    lv_obj_set_y(ui_btnCancelReturn, 77);
    lv_obj_set_align(ui_btnCancelReturn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCancelReturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCancelReturn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnCancelReturn, lv_color_hex(0xCACCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnCancelReturn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnCancelReturn, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnCancelReturn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnCancelReturn, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnCancelReturn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnCancelReturn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnCancelReturn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_btnCancelReturn);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "Cancel");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton10, ui_event_ImgButton10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnCancelReturn, ui_event_btnCancelReturn, LV_EVENT_ALL, NULL);

}

void ui_screenReturnScan_screen_destroy(void)
{
    if(ui_screenReturnScan) lv_obj_del(ui_screenReturnScan);

    // NULL screen variables
    ui_screenReturnScan = NULL;
    ui_Container4 = NULL;
    ui_Image14 = NULL;
    ui_Label36 = NULL;
    ui_ImgButton10 = NULL;
    ui_Label41 = NULL;
    ui_Image18 = NULL;
    ui_Label42 = NULL;
    ui_btnCancelReturn = NULL;
    ui_Label43 = NULL;

}
