// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENCREATEBILL_H
#define UI_SCREENCREATEBILL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenCreateBill
extern void ui_screenCreateBill_screen_init(void);
extern void ui_screenCreateBill_screen_destroy(void);
extern lv_obj_t * ui_screenCreateBill;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Label69;
extern void ui_event_ImgButton15(lv_event_t * e);
extern lv_obj_t * ui_ImgButton15;
extern lv_obj_t * ui_Container12;
extern void ui_event_btnBillContinue(lv_event_t * e);
extern lv_obj_t * ui_btnBillContinue;
extern lv_obj_t * ui_Label70;
extern void ui_event_btnBackCI2(lv_event_t * e);
extern lv_obj_t * ui_btnBackCI2;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_LabelCBProducts;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

