// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_screenPriceOfProduct = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_Label64 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
lv_obj_t * ui_Label62 = NULL;
lv_obj_t * ui_ProductDetailsPC = NULL;
lv_obj_t * ui_Label66 = NULL;
// event funtions
void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_screenPriceOfProduct_screen_init(void)
{
    ui_screenPriceOfProduct = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenPriceOfProduct, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenPriceOfProduct, lv_color_hex(0xFBBF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenPriceOfProduct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenPriceOfProduct, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenPriceOfProduct, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_screenPriceOfProduct);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 297);
    lv_obj_set_height(ui_Container14, 154);
    lv_obj_set_x(ui_Container14, 0);
    lv_obj_set_y(ui_Container14, 30);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container14, 190, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container14, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Container14, 99, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Container14, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_screenPriceOfProduct);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 312);
    lv_obj_set_height(ui_Container15, 50);
    lv_obj_set_x(ui_Container15, 0);
    lv_obj_set_y(ui_Container15, -85);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_img_create(ui_Container15);
    lv_img_set_src(ui_Image25, &ui_img_check_price_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image25, -91);
    lv_obj_set_y(ui_Image25, 0);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label64 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, 44);
    lv_obj_set_y(ui_Label64, 0);
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "Price Checker");
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label64, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton6 = lv_imgbtn_create(ui_screenPriceOfProduct);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton6, 30);
    lv_obj_set_height(ui_ImgButton6, 30);
    lv_obj_set_x(ui_ImgButton6, -134);
    lv_obj_set_y(ui_ImgButton6, -85);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_Label62 = lv_label_create(ui_screenPriceOfProduct);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, 0);
    lv_obj_set_y(ui_Label62, -26);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "Product Found Successfully");

    ui_ProductDetailsPC = lv_label_create(ui_screenPriceOfProduct);
    lv_obj_set_width(ui_ProductDetailsPC, 139);
    lv_obj_set_height(ui_ProductDetailsPC, 84);
    lv_obj_set_x(ui_ProductDetailsPC, 71);
    lv_obj_set_y(ui_ProductDetailsPC, 36);
    lv_obj_set_align(ui_ProductDetailsPC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProductDetailsPC, "");
    lv_obj_set_style_text_letter_space(ui_ProductDetailsPC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ProductDetailsPC, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label66 = lv_label_create(ui_screenPriceOfProduct);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label66, -67);
    lv_obj_set_y(ui_Label66, 36);
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "Product Name      :\nProduct Quantity :\nProduct MRP         :\nProduct Price        :");
    lv_obj_set_style_text_letter_space(ui_Label66, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label66, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);

}

void ui_screenPriceOfProduct_screen_destroy(void)
{
    if(ui_screenPriceOfProduct) lv_obj_del(ui_screenPriceOfProduct);

    // NULL screen variables
    ui_screenPriceOfProduct = NULL;
    ui_Container14 = NULL;
    ui_Container15 = NULL;
    ui_Image25 = NULL;
    ui_Label64 = NULL;
    ui_ImgButton6 = NULL;
    ui_Label62 = NULL;
    ui_ProductDetailsPC = NULL;
    ui_Label66 = NULL;

}
