// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENPRICEOFPRODUCT_H
#define UI_SCREENPRICEOFPRODUCT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenPriceOfProduct
extern void ui_screenPriceOfProduct_screen_init(void);
extern void ui_screenPriceOfProduct_screen_destroy(void);
extern lv_obj_t * ui_screenPriceOfProduct;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Label64;
extern void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_ProductDetailsPC;
extern lv_obj_t * ui_Label66;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

