// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Smart_LIbrary_Management

#ifndef _SMART_LIBRARY_MANAGEMENT_UI_H
#define _SMART_LIBRARY_MANAGEMENT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#pragma once
#include "api_findbook.h"
#include "keyboard.h"  // ensure keyboard header is included

// Globals used to pass find-book result between screens
extern char g_findbook_rack[16];
extern int  g_findbook_row;
extern int  g_findbook_column;
extern char g_findbook_name[128];
extern char  g_findbook_type_id[16];
extern char g_findbook_side[8];

extern char API_BASE_SERVER[64];


///////////////////// SCREENS ////////////////////

#include "screens/ui_screenLoader.h"
#include "screens/ui_screenHome.h"
#include "screens/ui_screenFindBook.h"
#include "screens/ui_screenFindBookInfo.h"
#include "screens/ui_screenIssueScan.h"
#include "screens/ui_screenIssueEnrollment.h"
#include "screens/ui_screenIssueFinalConfirm.h"
#include "screens/ui_screenIssueOtp.h"
#include "screens/ui_screenIssueOtpSuccess.h"
#include "screens/ui_screenIssueOtpFail.h"
#include "screens/ui_screenReturnScan.h"
#include "screens/ui_screenReturnSuccess.h"
#include "screens/ui_screenAbout.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * LoadingAnimationLogo_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LoadingAnimationText_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Opacity1_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_fmb_logo_png);    // assets/FMB Logo.png
LV_IMG_DECLARE(ui_img_fmb_text_png);    // assets/FMB Text.png
LV_IMG_DECLARE(ui_img_find_book_icon_png);    // assets/find book icon.png
LV_IMG_DECLARE(ui_img_return_book_icon_png);    // assets/return book icon.png
LV_IMG_DECLARE(ui_img_issue_book_icon_png);    // assets/issue book icon.png
LV_IMG_DECLARE(ui_img_about_us_icon_png);    // assets/About Us icon.png
LV_IMG_DECLARE(ui_img_mic_png);    // assets/mic.png
LV_IMG_DECLARE(ui_img_backbtn_png);    // assets/backBtn.png
LV_IMG_DECLARE(ui_img_backpressed_png);    // assets/backpressed.png
LV_IMG_DECLARE(ui_img_cross_png);    // assets/cross.png
LV_IMG_DECLARE(ui_img_rfidicon_png);    // assets/RFIDicon.png
LV_IMG_DECLARE(ui_img_success_png);    // assets/success.png
LV_IMG_DECLARE(ui_img_failed_png);    // assets/Failed.png
LV_IMG_DECLARE(ui_img_map_a_right_png);    // assets/map_A_right.png
LV_IMG_DECLARE(ui_img_map_a_left_png);    // assets/map_A_left.png
LV_IMG_DECLARE(ui_img_map_b_left_png);    // assets/map_B_left.png
LV_IMG_DECLARE(ui_img_map_b_right_png);    // assets/map_B_right.png
LV_IMG_DECLARE(ui_img_qr_ar1c1l_png);    // assets/QR/Ar1c1l.png
LV_IMG_DECLARE(ui_img_qr_ar1c1r_png);    // assets/QR/Ar1c1r.png
LV_IMG_DECLARE(ui_img_qr_ar1c2l_png);    // assets/QR/Ar1c2l.png
LV_IMG_DECLARE(ui_img_qr_ar1c2r_png);    // assets/QR/Ar1c2r.png
LV_IMG_DECLARE(ui_img_qr_ar2c1l_png);    // assets/QR/Ar2c1l.png
LV_IMG_DECLARE(ui_img_qr_ar2c1r_png);    // assets/QR/Ar2c1r.png
LV_IMG_DECLARE(ui_img_qr_ar2c2l_png);    // assets/QR/Ar2c2l.png
LV_IMG_DECLARE(ui_img_qr_ar2c2r_png);    // assets/QR/Ar2c2r.png
LV_IMG_DECLARE(ui_img_qr_br1c1l_png);    // assets/QR/Br1c1l.png
LV_IMG_DECLARE(ui_img_qr_br1c1r_png);    // assets/QR/Br1c1r.png
LV_IMG_DECLARE(ui_img_qr_br1c2l_png);    // assets/QR/Br1c2l.png
LV_IMG_DECLARE(ui_img_qr_br1c2r_png);    // assets/QR/Br1c2r.png
LV_IMG_DECLARE(ui_img_qr_br2c1l_png);    // assets/QR/Br2c1l.png
LV_IMG_DECLARE(ui_img_qr_br2c1r_png);    // assets/QR/Br2c1r.png
LV_IMG_DECLARE(ui_img_qr_br2c2l_png);    // assets/QR/Br2c2l.png
LV_IMG_DECLARE(ui_img_qr_br2c2r_png);    // assets/QR/Br2c2r.png


// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
