// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * uic_Button7;
lv_obj_t * ui_screenFindBookInfo = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_labelBDBookName = NULL;
lv_obj_t * ui_labelBDStatus = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_labelBDBookCode = NULL;
lv_obj_t * ui_labelBDLocation = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_btnBlinkShelf = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_btnBlinkBook = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_btnShowBookLocation = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_btnOpenOnPhone = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_MapFullContainer = NULL;
lv_obj_t * ui_imgMapLocationcont = NULL;
lv_obj_t * ui_imgMapLocation = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_QrFullContainer = NULL;
lv_obj_t * ui_imgQrCode = NULL;
lv_obj_t * ui_imgQR = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
// event funtions
void ui_event_screenFindBookInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_opacity_set(ui_QrFullContainer, 0);
        _ui_opacity_set(ui_MapFullContainer, 0);
    }
}

void ui_event_btnShowBookLocation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_opacity_set(ui_MapFullContainer, 255);
    }
}

void ui_event_btnOpenOnPhone(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_opacity_set(ui_QrFullContainer, 255);
    }
}

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenFindBook, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenFindBook_screen_init);
    }
}

void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_opacity_set(ui_MapFullContainer, 0);
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_opacity_set(ui_QrFullContainer, 0);
    }
}

// build funtions

void ui_screenFindBookInfo_screen_init(void)
{
    ui_screenFindBookInfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenFindBookInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenFindBookInfo, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenFindBookInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenFindBookInfo, lv_color_hex(0x3DB0E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenFindBookInfo, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_screenFindBookInfo);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -92);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Book Details");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_screenFindBookInfo);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 297);
    lv_obj_set_height(ui_Container6, 201);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 30);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 190, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container6, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_screenFindBookInfo);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -82);
    lv_obj_set_y(ui_Label12, -47);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Book Name :");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBDBookName = lv_label_create(ui_screenFindBookInfo);
    lv_obj_set_width(ui_labelBDBookName, 163);
    lv_obj_set_height(ui_labelBDBookName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBDBookName, 52);
    lv_obj_set_y(ui_labelBDBookName, -48);
    lv_obj_set_align(ui_labelBDBookName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBDBookName, "");
    lv_obj_set_style_text_align(ui_labelBDBookName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBDStatus = lv_label_create(ui_screenFindBookInfo);
    lv_obj_set_width(ui_labelBDStatus, 252);
    lv_obj_set_height(ui_labelBDStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBDStatus, 1);
    lv_obj_set_y(ui_labelBDStatus, -9);
    lv_obj_set_align(ui_labelBDStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBDStatus, "Available");
    lv_obj_set_style_text_color(ui_labelBDStatus, lv_color_hex(0x00C218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBDStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelBDStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_screenFindBookInfo);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -81);
    lv_obj_set_y(ui_Label7, -30);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Book Code :  ");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBDBookCode = lv_label_create(ui_screenFindBookInfo);
    lv_obj_set_width(ui_labelBDBookCode, 161);
    lv_obj_set_height(ui_labelBDBookCode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBDBookCode, 51);
    lv_obj_set_y(ui_labelBDBookCode, -29);
    lv_obj_set_align(ui_labelBDBookCode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBDBookCode, "");
    lv_obj_set_style_text_align(ui_labelBDBookCode, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBDLocation = lv_label_create(ui_screenFindBookInfo);
    lv_obj_set_width(ui_labelBDLocation, 236);
    lv_obj_set_height(ui_labelBDLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBDLocation, -7);
    lv_obj_set_y(ui_labelBDLocation, 9);
    lv_obj_set_align(ui_labelBDLocation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBDLocation, "ABCD");
    lv_obj_set_style_text_color(ui_labelBDLocation, lv_color_hex(0x00C218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBDLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelBDLocation, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_screenFindBookInfo);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 288);
    lv_obj_set_height(ui_Container7, 98);
    lv_obj_set_x(ui_Container7, 0);
    lv_obj_set_y(ui_Container7, 62);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnBlinkShelf = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_btnBlinkShelf, 115);
    lv_obj_set_height(ui_btnBlinkShelf, 32);
    lv_obj_set_x(ui_btnBlinkShelf, -69);
    lv_obj_set_y(ui_btnBlinkShelf, -22);
    lv_obj_set_align(ui_btnBlinkShelf, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBlinkShelf, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBlinkShelf, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBlinkShelf, lv_color_hex(0x2C30DF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBlinkShelf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnBlinkShelf, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnBlinkShelf, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnBlinkShelf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnBlinkShelf, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBlinkShelf, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBlinkShelf, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnBlinkShelf, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnBlinkShelf, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnBlinkShelf, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnBlinkShelf, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_btnBlinkShelf);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Blink Shelf");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBlinkBook = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_btnBlinkBook, 115);
    lv_obj_set_height(ui_btnBlinkBook, 32);
    lv_obj_set_x(ui_btnBlinkBook, 69);
    lv_obj_set_y(ui_btnBlinkBook, -22);
    lv_obj_set_align(ui_btnBlinkBook, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBlinkBook, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBlinkBook, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBlinkBook, lv_color_hex(0x2C30DF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBlinkBook, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnBlinkBook, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnBlinkBook, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnBlinkBook, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnBlinkBook, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBlinkBook, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBlinkBook, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnBlinkBook, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnBlinkBook, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnBlinkBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnBlinkBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_btnBlinkBook);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Blink Book");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnShowBookLocation = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_btnShowBookLocation, 115);
    lv_obj_set_height(ui_btnShowBookLocation, 32);
    lv_obj_set_x(ui_btnShowBookLocation, -69);
    lv_obj_set_y(ui_btnShowBookLocation, 26);
    lv_obj_set_align(ui_btnShowBookLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnShowBookLocation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnShowBookLocation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnShowBookLocation, lv_color_hex(0x2C30DF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnShowBookLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnShowBookLocation, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnShowBookLocation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnShowBookLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnShowBookLocation, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnShowBookLocation, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnShowBookLocation, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnShowBookLocation, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnShowBookLocation, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnShowBookLocation, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnShowBookLocation, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_btnShowBookLocation);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Location Map");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnOpenOnPhone = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_btnOpenOnPhone, 115);
    lv_obj_set_height(ui_btnOpenOnPhone, 32);
    lv_obj_set_x(ui_btnOpenOnPhone, 69);
    lv_obj_set_y(ui_btnOpenOnPhone, 26);
    lv_obj_set_align(ui_btnOpenOnPhone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnOpenOnPhone, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnOpenOnPhone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnOpenOnPhone, lv_color_hex(0x2C30DF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOpenOnPhone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnOpenOnPhone, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnOpenOnPhone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnOpenOnPhone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnOpenOnPhone, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnOpenOnPhone, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnOpenOnPhone, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnOpenOnPhone, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnOpenOnPhone, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnOpenOnPhone, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnOpenOnPhone, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_btnOpenOnPhone);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Open On \nPhone");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_screenFindBookInfo);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 30);
    lv_obj_set_height(ui_ImgButton2, 30);
    lv_obj_set_x(ui_ImgButton2, -134);
    lv_obj_set_y(ui_ImgButton2, -91);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_MapFullContainer = lv_obj_create(ui_screenFindBookInfo);
    lv_obj_remove_style_all(ui_MapFullContainer);
    lv_obj_set_width(ui_MapFullContainer, 361);
    lv_obj_set_height(ui_MapFullContainer, 251);
    lv_obj_set_align(ui_MapFullContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MapFullContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MapFullContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MapFullContainer, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MapFullContainer, 210, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMapLocationcont = lv_obj_create(ui_MapFullContainer);
    lv_obj_remove_style_all(ui_imgMapLocationcont);
    lv_obj_set_width(ui_imgMapLocationcont, 245);
    lv_obj_set_height(ui_imgMapLocationcont, 209);
    lv_obj_set_x(ui_imgMapLocationcont, 0);
    lv_obj_set_y(ui_imgMapLocationcont, 1);
    lv_obj_set_align(ui_imgMapLocationcont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgMapLocationcont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imgMapLocationcont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imgMapLocationcont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMapLocation = lv_img_create(ui_imgMapLocationcont);
    lv_obj_set_width(ui_imgMapLocation, 225);
    lv_obj_set_height(ui_imgMapLocation, 192);
    lv_obj_set_align(ui_imgMapLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMapLocation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMapLocation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton4 = lv_imgbtn_create(ui_MapFullContainer);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cross_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cross_png, NULL);
    lv_obj_set_width(ui_ImgButton4, 15);
    lv_obj_set_height(ui_ImgButton4, 14);
    lv_obj_set_x(ui_ImgButton4, -138);
    lv_obj_set_y(ui_ImgButton4, -73);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_QrFullContainer = lv_obj_create(ui_screenFindBookInfo);
    lv_obj_remove_style_all(ui_QrFullContainer);
    lv_obj_set_width(ui_QrFullContainer, 361);
    lv_obj_set_height(ui_QrFullContainer, 251);
    lv_obj_set_align(ui_QrFullContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QrFullContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_QrFullContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_QrFullContainer, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QrFullContainer, 210, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgQrCode = lv_obj_create(ui_QrFullContainer);
    lv_obj_remove_style_all(ui_imgQrCode);
    lv_obj_set_width(ui_imgQrCode, 120);
    lv_obj_set_height(ui_imgQrCode, 120);
    lv_obj_set_x(ui_imgQrCode, 0);
    lv_obj_set_y(ui_imgQrCode, -28);
    lv_obj_set_align(ui_imgQrCode, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgQrCode, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imgQrCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imgQrCode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgQR = lv_img_create(ui_imgQrCode);
    lv_obj_set_width(ui_imgQR, lv_pct(90));
    lv_obj_set_height(ui_imgQR, lv_pct(90));
    lv_obj_set_align(ui_imgQR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgQR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgQR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_QrFullContainer);
    lv_obj_set_width(ui_Label17, 201);
    lv_obj_set_height(ui_Label17, 37);
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, 66);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Scan this QR code to view navigation on your phone");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label17, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label17, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_QrFullContainer);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cross_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cross_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 15);
    lv_obj_set_height(ui_ImgButton1, 14);
    lv_obj_set_x(ui_ImgButton1, -118);
    lv_obj_set_y(ui_ImgButton1, -91);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_btnShowBookLocation, ui_event_btnShowBookLocation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnOpenOnPhone, ui_event_btnOpenOnPhone, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenFindBookInfo, ui_event_screenFindBookInfo, LV_EVENT_ALL, NULL);
    uic_Button7 = ui_btnBlinkShelf;

}

void ui_screenFindBookInfo_screen_destroy(void)
{
    if(ui_screenFindBookInfo) lv_obj_del(ui_screenFindBookInfo);

    // NULL screen variables
    ui_screenFindBookInfo = NULL;
    ui_Label11 = NULL;
    ui_Container6 = NULL;
    ui_Label12 = NULL;
    ui_labelBDBookName = NULL;
    ui_labelBDStatus = NULL;
    ui_Label7 = NULL;
    ui_labelBDBookCode = NULL;
    ui_labelBDLocation = NULL;
    ui_Container7 = NULL;
    uic_Button7 = NULL;
    ui_btnBlinkShelf = NULL;
    ui_Label14 = NULL;
    ui_btnBlinkBook = NULL;
    ui_Label13 = NULL;
    ui_btnShowBookLocation = NULL;
    ui_Label28 = NULL;
    ui_btnOpenOnPhone = NULL;
    ui_Label15 = NULL;
    ui_ImgButton2 = NULL;
    ui_MapFullContainer = NULL;
    ui_imgMapLocationcont = NULL;
    ui_imgMapLocation = NULL;
    ui_ImgButton4 = NULL;
    ui_QrFullContainer = NULL;
    ui_imgQrCode = NULL;
    ui_imgQR = NULL;
    ui_Label17 = NULL;
    ui_ImgButton1 = NULL;

}
