// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Smart_LIbrary_Management

#include "../ui.h"

lv_obj_t * ui_screenIssueFinalConfirm = NULL;
lv_obj_t * ui_ImgButton11 = NULL;
lv_obj_t * ui_Label48 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_labelsiBookName = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_labelsiBookCode = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_labelsiUserName = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_labelsiDueDate = NULL;
lv_obj_t * ui_btnConfirmIssue = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_btnBackCI = NULL;
lv_obj_t * ui_Label54 = NULL;
// event funtions
void ui_event_ImgButton11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenIssueEnrollment, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenIssueEnrollment_screen_init);
    }
}

void ui_event_btnConfirmIssue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenIssueOtp, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_screenIssueOtp_screen_init);
    }
}

void ui_event_btnBackCI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenIssueEnrollment, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenIssueEnrollment_screen_init);
    }
}

// build funtions

void ui_screenIssueFinalConfirm_screen_init(void)
{
    ui_screenIssueFinalConfirm = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenIssueFinalConfirm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenIssueFinalConfirm, lv_color_hex(0xFBBF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenIssueFinalConfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenIssueFinalConfirm, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenIssueFinalConfirm, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton11 = lv_imgbtn_create(ui_screenIssueFinalConfirm);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton11, 30);
    lv_obj_set_height(ui_ImgButton11, 30);
    lv_obj_set_x(ui_ImgButton11, -134);
    lv_obj_set_y(ui_ImgButton11, -91);
    lv_obj_set_align(ui_ImgButton11, LV_ALIGN_CENTER);

    ui_Label48 = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 0);
    lv_obj_set_y(ui_Label48, -92);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "Confirm Issue");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_screenIssueFinalConfirm);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 297);
    lv_obj_set_height(ui_Container10, 201);
    lv_obj_set_x(ui_Container10, 0);
    lv_obj_set_y(ui_Container10, 30);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container10, 190, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container10, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -82);
    lv_obj_set_y(ui_Label49, -47);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "Book Name :");
    lv_obj_set_style_text_align(ui_Label49, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelsiBookName = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_labelsiBookName, 163);
    lv_obj_set_height(ui_labelsiBookName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelsiBookName, 52);
    lv_obj_set_y(ui_labelsiBookName, -48);
    lv_obj_set_align(ui_labelsiBookName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelsiBookName, "");
    lv_obj_set_style_text_align(ui_labelsiBookName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -81);
    lv_obj_set_y(ui_Label50, -30);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "Book Code :  ");
    lv_obj_set_style_text_align(ui_Label50, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelsiBookCode = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_labelsiBookCode, 161);
    lv_obj_set_height(ui_labelsiBookCode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelsiBookCode, 51);
    lv_obj_set_y(ui_labelsiBookCode, -29);
    lv_obj_set_align(ui_labelsiBookCode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelsiBookCode, "");
    lv_obj_set_style_text_align(ui_labelsiBookCode, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -106);
    lv_obj_set_y(ui_Label51, -11);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "User : ");
    lv_obj_set_style_text_align(ui_Label51, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelsiUserName = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_labelsiUserName, 161);
    lv_obj_set_height(ui_labelsiUserName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelsiUserName, 3);
    lv_obj_set_y(ui_labelsiUserName, -11);
    lv_obj_set_align(ui_labelsiUserName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelsiUserName, "");
    lv_obj_set_style_text_align(ui_labelsiUserName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, -89);
    lv_obj_set_y(ui_Label47, 6);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "Due Date :");
    lv_obj_set_style_text_align(ui_Label47, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelsiDueDate = lv_label_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_labelsiDueDate, 161);
    lv_obj_set_height(ui_labelsiDueDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelsiDueDate, 38);
    lv_obj_set_y(ui_labelsiDueDate, 6);
    lv_obj_set_align(ui_labelsiDueDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelsiDueDate, "");
    lv_obj_set_style_text_align(ui_labelsiDueDate, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnConfirmIssue = lv_btn_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_btnConfirmIssue, 234);
    lv_obj_set_height(ui_btnConfirmIssue, 32);
    lv_obj_set_x(ui_btnConfirmIssue, 0);
    lv_obj_set_y(ui_btnConfirmIssue, 46);
    lv_obj_set_align(ui_btnConfirmIssue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnConfirmIssue, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnConfirmIssue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnConfirmIssue, lv_color_hex(0x2C30DF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConfirmIssue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnConfirmIssue, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnConfirmIssue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnConfirmIssue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnConfirmIssue, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnConfirmIssue, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnConfirmIssue, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnConfirmIssue, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnConfirmIssue, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnConfirmIssue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnConfirmIssue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_btnConfirmIssue);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "Confirm Issue");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackCI = lv_btn_create(ui_screenIssueFinalConfirm);
    lv_obj_set_width(ui_btnBackCI, 234);
    lv_obj_set_height(ui_btnBackCI, 32);
    lv_obj_set_x(ui_btnBackCI, 0);
    lv_obj_set_y(ui_btnBackCI, 89);
    lv_obj_set_align(ui_btnBackCI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBackCI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBackCI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackCI, lv_color_hex(0x6265EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackCI, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnBackCI, lv_color_hex(0x8D8DBB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnBackCI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnBackCI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnBackCI, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackCI, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackCI, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnBackCI, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnBackCI, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnBackCI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnBackCI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_btnBackCI);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "Back");
    lv_obj_set_style_text_color(ui_Label54, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton11, ui_event_ImgButton11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnConfirmIssue, ui_event_btnConfirmIssue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBackCI, ui_event_btnBackCI, LV_EVENT_ALL, NULL);

}

void ui_screenIssueFinalConfirm_screen_destroy(void)
{
    if(ui_screenIssueFinalConfirm) lv_obj_del(ui_screenIssueFinalConfirm);

    // NULL screen variables
    ui_screenIssueFinalConfirm = NULL;
    ui_ImgButton11 = NULL;
    ui_Label48 = NULL;
    ui_Container10 = NULL;
    ui_Label49 = NULL;
    ui_labelsiBookName = NULL;
    ui_Label50 = NULL;
    ui_labelsiBookCode = NULL;
    ui_Label51 = NULL;
    ui_labelsiUserName = NULL;
    ui_Label47 = NULL;
    ui_labelsiDueDate = NULL;
    ui_btnConfirmIssue = NULL;
    ui_Label53 = NULL;
    ui_btnBackCI = NULL;
    ui_Label54 = NULL;

}
