// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENABOUT_H
#define UI_SCREENABOUT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenAbout
extern void ui_screenAbout_screen_init(void);
extern void ui_screenAbout_screen_destroy(void);
extern lv_obj_t * ui_screenAbout;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label40;
extern void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

