// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_screenAbout = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Label46 = NULL;
// event funtions
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_screenAbout_screen_init(void)
{
    ui_screenAbout = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenAbout, lv_color_hex(0xA5B4FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenAbout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenAbout, lv_color_hex(0x6366F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenAbout, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_screenAbout);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 312);
    lv_obj_set_height(ui_Container8, 50);
    lv_obj_set_x(ui_Container8, 0);
    lv_obj_set_y(ui_Container8, -85);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Container8);
    lv_img_set_src(ui_Image16, &ui_img_about_us_icon_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image16, -77);
    lv_obj_set_y(ui_Image16, 0);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 36);
    lv_obj_set_y(ui_Label40, 0);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "About Us");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton5 = lv_imgbtn_create(ui_screenAbout);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton5, 30);
    lv_obj_set_height(ui_ImgButton5, 30);
    lv_obj_set_x(ui_ImgButton5, -134);
    lv_obj_set_y(ui_ImgButton5, -85);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_screenAbout);
    lv_obj_set_width(ui_Panel1, 283);
    lv_obj_set_height(ui_Panel1, 170);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 29);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);

    ui_Label39 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 0);
    lv_obj_set_y(ui_Label39, -62);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "About FindMyBook (FMB)");

    ui_Label44 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label44, 240);
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, 0);
    lv_obj_set_y(ui_Label44, 27);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44,
                      "FindMyBook (FMB) is a smart library navigation and automation system\ndesigned to help users find, issue, and return books quickly and efficiently.\n\nBy combining AI, IoT, RFID, and intelligent shelf guidance,\nFMB reduces search time and improves overall library experience.\n");
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 0);
    lv_obj_set_y(ui_Label45, 109);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "About the Creator");

    ui_Label46 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label46, 240);
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 0);
    lv_obj_set_y(ui_Label46, 178);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46,
                      "FindMyBook is designed and developed by Aman Gandotra,\na student innovator focused on building practical technology solutions\nfor real-world problems using AI, IoT, and embedded systems.\n");
    lv_obj_set_style_text_font(ui_Label46, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);

}

void ui_screenAbout_screen_destroy(void)
{
    if(ui_screenAbout) lv_obj_del(ui_screenAbout);

    // NULL screen variables
    ui_screenAbout = NULL;
    ui_Container8 = NULL;
    ui_Image16 = NULL;
    ui_Label40 = NULL;
    ui_ImgButton5 = NULL;
    ui_Panel1 = NULL;
    ui_Label39 = NULL;
    ui_Label44 = NULL;
    ui_Label45 = NULL;
    ui_Label46 = NULL;

}
