// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_screenIssueScan = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_ImgButton7 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_btnCancelIssue = NULL;
lv_obj_t * ui_Label21 = NULL;
// event funtions
void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

void ui_event_btnCancelIssue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_screenIssueScan_screen_init(void)
{
    ui_screenIssueScan = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenIssueScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenIssueScan, lv_color_hex(0xFBBF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenIssueScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenIssueScan, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenIssueScan, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_screenIssueScan);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 312);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, -85);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Container3);
    lv_img_set_src(ui_Image2, &ui_img_issue_book_icon_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image2, -81);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 36);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Issue Book");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton7 = lv_imgbtn_create(ui_screenIssueScan);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton7, 30);
    lv_obj_set_height(ui_ImgButton7, 30);
    lv_obj_set_x(ui_ImgButton7, -134);
    lv_obj_set_y(ui_ImgButton7, -85);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);

    ui_Label18 = lv_label_create(ui_screenIssueScan);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, -48);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Please scan book RFID");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x010045), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_img_create(ui_screenIssueScan);
    lv_img_set_src(ui_Image17, &ui_img_rfidicon_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 112
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 58
    lv_obj_set_x(ui_Image17, 0);
    lv_obj_set_y(ui_Image17, 3);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_screenIssueScan);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 43);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Waiting for RFID....");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x125400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCancelIssue = lv_btn_create(ui_screenIssueScan);
    lv_obj_set_width(ui_btnCancelIssue, 256);
    lv_obj_set_height(ui_btnCancelIssue, 40);
    lv_obj_set_x(ui_btnCancelIssue, 0);
    lv_obj_set_y(ui_btnCancelIssue, 77);
    lv_obj_set_align(ui_btnCancelIssue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCancelIssue, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCancelIssue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnCancelIssue, lv_color_hex(0xCACCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnCancelIssue, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnCancelIssue, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnCancelIssue, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnCancelIssue, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnCancelIssue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnCancelIssue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnCancelIssue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_btnCancelIssue);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Cancel");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnCancelIssue, ui_event_btnCancelIssue, LV_EVENT_ALL, NULL);

}

void ui_screenIssueScan_screen_destroy(void)
{
    if(ui_screenIssueScan) lv_obj_del(ui_screenIssueScan);

    // NULL screen variables
    ui_screenIssueScan = NULL;
    ui_Container3 = NULL;
    ui_Image2 = NULL;
    ui_Label8 = NULL;
    ui_ImgButton7 = NULL;
    ui_Label18 = NULL;
    ui_Image17 = NULL;
    ui_Label19 = NULL;
    ui_btnCancelIssue = NULL;
    ui_Label21 = NULL;

}
