// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENLOADER_H
#define UI_SCREENLOADER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenLoader
extern void ui_screenLoader_screen_init(void);
extern void ui_screenLoader_screen_destroy(void);
extern void ui_event_screenLoader(lv_event_t * e);
extern lv_obj_t * ui_screenLoader;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

