// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENISSUEOTPSUCCESS_H
#define UI_SCREENISSUEOTPSUCCESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenIssueOtpSuccess
extern void ui_screenIssueOtpSuccess_screen_init(void);
extern void ui_screenIssueOtpSuccess_screen_destroy(void);
extern lv_obj_t * ui_screenIssueOtpSuccess;
extern void ui_event_btnissuedn(lv_event_t * e);
extern lv_obj_t * ui_btnissuedn;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

