// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENISSUESCAN_H
#define UI_SCREENISSUESCAN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenIssueScan
extern void ui_screenIssueScan_screen_init(void);
extern void ui_screenIssueScan_screen_destroy(void);
extern lv_obj_t * ui_screenIssueScan;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label8;
extern void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label19;
extern void ui_event_btnCancelIssue(lv_event_t * e);
extern lv_obj_t * ui_btnCancelIssue;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

