// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENFINDVOICE_H
#define UI_SCREENFINDVOICE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenFindVoice
extern void ui_ScreenFindVoice_screen_init(void);
extern void ui_ScreenFindVoice_screen_destroy(void);
extern lv_obj_t * ui_ScreenFindVoice;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Label60;
extern void ui_event_ImgButton13(lv_event_t * e);
extern lv_obj_t * ui_ImgButton13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

