// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENBILLCREATEDSUCCESS_H
#define UI_SCREENBILLCREATEDSUCCESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenBillCreatedSuccess
extern void ui_ScreenBillCreatedSuccess_screen_init(void);
extern void ui_ScreenBillCreatedSuccess_screen_destroy(void);
extern lv_obj_t * ui_ScreenBillCreatedSuccess;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_Label73;
extern lv_obj_t * ui_Label74;
extern lv_obj_t * ui_LabelTProHere;
extern lv_obj_t * ui_LabelTPriceHere;
extern lv_obj_t * ui_LabelUBI;
extern void ui_event_ImgButton16(lv_event_t * e);
extern lv_obj_t * ui_ImgButton16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

