// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENISSUEENROLLMENT_H
#define UI_SCREENISSUEENROLLMENT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenIssueEnrollment
extern void ui_screenIssueEnrollment_screen_init(void);
extern void ui_screenIssueEnrollment_screen_destroy(void);
extern lv_obj_t * ui_screenIssueEnrollment;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label26;
extern void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_taEnrollmentNum;
extern lv_obj_t * ui_btnCheckUser;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

