// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_ScreenBillCreatedSuccess = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_Label72 = NULL;
lv_obj_t * ui_Label73 = NULL;
lv_obj_t * ui_Label74 = NULL;
lv_obj_t * ui_LabelTProHere = NULL;
lv_obj_t * ui_LabelTPriceHere = NULL;
lv_obj_t * ui_LabelUBI = NULL;
lv_obj_t * ui_ImgButton16 = NULL;
// event funtions
void ui_event_ImgButton16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_ScreenBillCreatedSuccess_screen_init(void)
{
    ui_ScreenBillCreatedSuccess = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBillCreatedSuccess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenBillCreatedSuccess, lv_color_hex(0xA5B4FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenBillCreatedSuccess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenBillCreatedSuccess, lv_color_hex(0x6366F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenBillCreatedSuccess, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image27 = lv_img_create(ui_ScreenBillCreatedSuccess);
    lv_img_set_src(ui_Image27, &ui_img_billcreatedsuccess_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label72 = lv_label_create(ui_ScreenBillCreatedSuccess);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label72, -27);
    lv_obj_set_y(ui_Label72, 4);
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "Total Products");
    lv_obj_set_style_text_font(ui_Label72, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label73 = lv_label_create(ui_ScreenBillCreatedSuccess);
    lv_obj_set_width(ui_Label73, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label73, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label73, -38);
    lv_obj_set_y(ui_Label73, 29);
    lv_obj_set_align(ui_Label73, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label73, "Total Price");
    lv_obj_set_style_text_font(ui_Label73, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label74 = lv_label_create(ui_ScreenBillCreatedSuccess);
    lv_obj_set_width(ui_Label74, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label74, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label74, -29);
    lv_obj_set_y(ui_Label74, 56);
    lv_obj_set_align(ui_Label74, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label74, "Unique Bill ID");
    lv_obj_set_style_text_font(ui_Label74, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTProHere = lv_label_create(ui_ScreenBillCreatedSuccess);
    lv_obj_set_width(ui_LabelTProHere, 54);
    lv_obj_set_height(ui_LabelTProHere, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTProHere, 60);
    lv_obj_set_y(ui_LabelTProHere, 4);
    lv_obj_set_align(ui_LabelTProHere, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTProHere, "");

    ui_LabelTPriceHere = lv_label_create(ui_ScreenBillCreatedSuccess);
    lv_obj_set_width(ui_LabelTPriceHere, 54);
    lv_obj_set_height(ui_LabelTPriceHere, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTPriceHere, 60);
    lv_obj_set_y(ui_LabelTPriceHere, 29);
    lv_obj_set_align(ui_LabelTPriceHere, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTPriceHere, "");

    ui_LabelUBI = lv_label_create(ui_ScreenBillCreatedSuccess);
    lv_obj_set_width(ui_LabelUBI, 54);
    lv_obj_set_height(ui_LabelUBI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUBI, 60);
    lv_obj_set_y(ui_LabelUBI, 56);
    lv_obj_set_align(ui_LabelUBI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUBI, "");

    ui_ImgButton16 = lv_imgbtn_create(ui_ScreenBillCreatedSuccess);
    lv_imgbtn_set_src(ui_ImgButton16, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton16, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton16, 30);
    lv_obj_set_height(ui_ImgButton16, 30);
    lv_obj_set_x(ui_ImgButton16, -134);
    lv_obj_set_y(ui_ImgButton16, -85);
    lv_obj_set_align(ui_ImgButton16, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton16, ui_event_ImgButton16, LV_EVENT_ALL, NULL);

}

void ui_ScreenBillCreatedSuccess_screen_destroy(void)
{
    if(ui_ScreenBillCreatedSuccess) lv_obj_del(ui_ScreenBillCreatedSuccess);

    // NULL screen variables
    ui_ScreenBillCreatedSuccess = NULL;
    ui_Image27 = NULL;
    ui_Label72 = NULL;
    ui_Label73 = NULL;
    ui_Label74 = NULL;
    ui_LabelTProHere = NULL;
    ui_LabelTPriceHere = NULL;
    ui_LabelUBI = NULL;
    ui_ImgButton16 = NULL;

}
