// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENISSUEFINALCONFIRM_H
#define UI_SCREENISSUEFINALCONFIRM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenIssueFinalConfirm
extern void ui_screenIssueFinalConfirm_screen_init(void);
extern void ui_screenIssueFinalConfirm_screen_destroy(void);
extern lv_obj_t * ui_screenIssueFinalConfirm;
extern void ui_event_ImgButton11(lv_event_t * e);
extern lv_obj_t * ui_ImgButton11;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_labelsiBookName;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_labelsiBookCode;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_labelsiUserName;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_labelsiDueDate;
extern void ui_event_btnConfirmIssue(lv_event_t * e);
extern lv_obj_t * ui_btnConfirmIssue;
extern lv_obj_t * ui_Label53;
extern void ui_event_btnBackCI(lv_event_t * e);
extern lv_obj_t * ui_btnBackCI;
extern lv_obj_t * ui_Label54;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

