// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"
#include "rfid_service.h"
lv_obj_t * ui_screenHome = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_btnFindBook = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_btnReturnBook = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_btnIssueBook = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_btnAboutUs = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_screenHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_opacity_set(ui_btnAboutUs, 255);
        _ui_opacity_set(ui_btnIssueBook, 255);
        _ui_opacity_set(ui_btnReturnBook, 255);
        _ui_opacity_set(ui_btnFindBook, 255);
        rfid_set_mode(RFID_MODE_NONE);
        rfid_set_callback(NULL);

    }
}

void ui_event_btnFindBook(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenFindAGrocery, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 400, 0, &ui_ScreenFindAGrocery_screen_init);
        _ui_opacity_set(ui_btnAboutUs, 0);
        _ui_opacity_set(ui_btnIssueBook, 0);
        _ui_opacity_set(ui_btnReturnBook, 0);
    }
}

void ui_event_btnReturnBook(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_opacity_set(ui_btnAboutUs, 0);
        _ui_opacity_set(ui_btnIssueBook, 0);
        _ui_opacity_set(ui_btnFindBook, 0);
        _ui_screen_change(&ui_screenReturnScan, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 400, 0, &ui_screenReturnScan_screen_init);
    }
}

void ui_event_btnIssueBook(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_opacity_set(ui_btnAboutUs, 0);
        _ui_opacity_set(ui_btnReturnBook, 0);
        _ui_opacity_set(ui_btnFindBook, 0);
        _ui_screen_change(&ui_screenIssueScan, LV_SCR_LOAD_ANIM_MOVE_LEFT, 400, 0, &ui_screenIssueScan_screen_init);
    }
}

void ui_event_btnAboutUs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenAbout, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_screenAbout_screen_init);
        _ui_opacity_set(ui_btnReturnBook, 0);
        _ui_opacity_set(ui_btnIssueBook, 0);
        _ui_opacity_set(ui_btnFindBook, 0);
    }
}

// build funtions

void ui_screenHome_screen_init(void)
{
    ui_screenHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenHome, lv_color_hex(0x001362), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenHome, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_screenHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_screenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenHome, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_screenHome, lv_color_hex(0xE6ECFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_screenHome);
    lv_img_set_src(ui_Image5, &ui_img_fmg_logo_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -92);
    lv_obj_set_y(ui_Image5, -88);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 140);

    ui_Image6 = lv_img_create(ui_screenHome);
    lv_img_set_src(ui_Image6, &ui_img_fmg_text_png);
    lv_obj_set_height(ui_Image6, 40);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 199
    lv_obj_set_x(ui_Image6, 34);
    lv_obj_set_y(ui_Image6, -99);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 255);

    ui_Label1 = lv_label_create(ui_screenHome);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -54);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Welcome, Shopper. Tap an option to begin!");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
   
    ui_Label59 = lv_label_create(ui_screenHome);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, 0);
    lv_obj_set_y(ui_Label59, 106);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "Crafted with passion by Aman Gandotra");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0xC2CEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label59, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_screenHome);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 449);
    lv_obj_set_height(ui_Container2, 148);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 31);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnFindBook = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_btnFindBook, 199);
    lv_obj_set_height(ui_btnFindBook, 55);
    lv_obj_set_x(ui_btnFindBook, -120);
    lv_obj_set_y(ui_btnFindBook, -42);
    lv_obj_set_align(ui_btnFindBook, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFindBook, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnFindBook, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnFindBook, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnFindBook, lv_color_hex(0x3DB0E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnFindBook, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnFindBook, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnFindBook, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnFindBook, lv_color_hex(0x82A4EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnFindBook, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnFindBook, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnFindBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnFindBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnFindBook, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_btnFindBook);
    lv_img_set_src(ui_Image7, &ui_img_find_a_grocery_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image7, 62);
    lv_obj_set_y(ui_Image7, 2);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 200);

    ui_Label2 = lv_label_create(ui_btnFindBook);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 5);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Find a \nGrocery");
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnReturnBook = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_btnReturnBook, 230);
    lv_obj_set_height(ui_btnReturnBook, 55);
    lv_obj_set_x(ui_btnReturnBook, -136);
    lv_obj_set_y(ui_btnReturnBook, 34);
    lv_obj_set_align(ui_btnReturnBook, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnReturnBook, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnReturnBook, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnReturnBook, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnReturnBook, lv_color_hex(0x4ADE80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnReturnBook, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnReturnBook, lv_color_hex(0x16A34A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnReturnBook, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnReturnBook, lv_color_hex(0x7FECAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnReturnBook, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnReturnBook, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnReturnBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnReturnBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnReturnBook, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_btnReturnBook);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 25);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Product \nDetails");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_btnReturnBook);
    lv_img_set_src(ui_Image9, &ui_img_knowprice_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image9, 80);
    lv_obj_set_y(ui_Image9, -2);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 102);

    ui_btnIssueBook = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_btnIssueBook, 227);
    lv_obj_set_height(ui_btnIssueBook, 55);
    lv_obj_set_x(ui_btnIssueBook, 134);
    lv_obj_set_y(ui_btnIssueBook, -41);
    lv_obj_set_align(ui_btnIssueBook, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnIssueBook, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnIssueBook, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnIssueBook, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnIssueBook, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnIssueBook, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnIssueBook, lv_color_hex(0xFBBF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnIssueBook, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnIssueBook, lv_color_hex(0xFBBF90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnIssueBook, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnIssueBook, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnIssueBook, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnIssueBook, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnIssueBook, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_btnIssueBook);
    lv_img_set_src(ui_Image10, &ui_img_check_price_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 61
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_Image10, -81);
    lv_obj_set_y(ui_Image10, 0);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 200);

    ui_Label4 = lv_label_create(ui_btnIssueBook);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -21);
    lv_obj_set_y(ui_Label4, -1);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Check \nPrice");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnAboutUs = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_btnAboutUs, 202);
    lv_obj_set_height(ui_btnAboutUs, 55);
    lv_obj_set_x(ui_btnAboutUs, 122);
    lv_obj_set_y(ui_btnAboutUs, 34);
    lv_obj_set_align(ui_btnAboutUs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnAboutUs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnAboutUs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnAboutUs, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnAboutUs, lv_color_hex(0x6366F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnAboutUs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnAboutUs, lv_color_hex(0xA5B4FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnAboutUs, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnAboutUs, lv_color_hex(0xA0ACF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnAboutUs, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnAboutUs, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnAboutUs, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnAboutUs, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnAboutUs, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_btnAboutUs);
    lv_img_set_src(ui_Image11, &ui_img_makeorder_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 61
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 46
    lv_obj_set_x(ui_Image11, -71);
    lv_obj_set_y(ui_Image11, 2);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 200);

    ui_Label5 = lv_label_create(ui_btnAboutUs);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -11);
    lv_obj_set_y(ui_Label5, 1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Create \nBill");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnFindBook, ui_event_btnFindBook, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnReturnBook, ui_event_btnReturnBook, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnIssueBook, ui_event_btnIssueBook, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnAboutUs, ui_event_btnAboutUs, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenHome, ui_event_screenHome, LV_EVENT_ALL, NULL);
    rfid_set_mode(RFID_MODE_NONE);
    rfid_set_callback(NULL);
}

void ui_screenHome_screen_destroy(void)
{
    if(ui_screenHome) lv_obj_del(ui_screenHome);

    // NULL screen variables
    ui_screenHome = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Label1 = NULL;
    ui_Label59 = NULL;
    ui_Container2 = NULL;
    ui_btnFindBook = NULL;
    ui_Image7 = NULL;
    ui_Label2 = NULL;
    ui_btnReturnBook = NULL;
    ui_Label3 = NULL;
    ui_Image9 = NULL;
    ui_btnIssueBook = NULL;
    ui_Image10 = NULL;
    ui_Label4 = NULL;
    ui_btnAboutUs = NULL;
    ui_Image11 = NULL;
    ui_Label5 = NULL;

}
