// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_screenProductDetails = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_Label67 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Label65 = NULL;
lv_obj_t * ui_LabelWIS = NULL;
lv_obj_t * ui_ImgButton17 = NULL;
// event funtions
void ui_event_ImgButton17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

// build funtions

void ui_screenProductDetails_screen_init(void)
{
    ui_screenProductDetails = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenProductDetails, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenProductDetails, lv_color_hex(0x16A34A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenProductDetails, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenProductDetails, lv_color_hex(0x4ADE80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenProductDetails, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_screenProductDetails);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 312);
    lv_obj_set_height(ui_Container16, 50);
    lv_obj_set_x(ui_Container16, 20);
    lv_obj_set_y(ui_Container16, -94);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_img_create(ui_Container16);
    lv_img_set_src(ui_Image26, &ui_img_knowprice_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image26, -116);
    lv_obj_set_y(ui_Image26, 0);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image26, 100);

    ui_Label67 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, 19);
    lv_obj_set_y(ui_Label67, 0);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "Product Details");
    lv_obj_set_style_text_color(ui_Label67, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label67, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_img_create(ui_screenProductDetails);
    lv_img_set_src(ui_Image21, &ui_img_pdcam_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Image21, -1);
    lv_obj_set_y(ui_Image21, -9);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image21, 180);

    ui_Label65 = lv_label_create(ui_screenProductDetails);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, 0);
    lv_obj_set_y(ui_Label65, 70);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "Show the Product in front of camera\nto know about the product");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0x043002), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label65, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWIS = lv_label_create(ui_screenProductDetails);
    lv_obj_set_width(ui_LabelWIS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWIS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWIS, 0);
    lv_obj_set_y(ui_LabelWIS, 98);
    lv_obj_set_align(ui_LabelWIS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWIS, "");

    ui_ImgButton17 = lv_imgbtn_create(ui_screenProductDetails);
    lv_imgbtn_set_src(ui_ImgButton17, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton17, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton17, 30);
    lv_obj_set_height(ui_ImgButton17, 30);
    lv_obj_set_x(ui_ImgButton17, -135);
    lv_obj_set_y(ui_ImgButton17, -90);
    lv_obj_set_align(ui_ImgButton17, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton17, ui_event_ImgButton17, LV_EVENT_ALL, NULL);

}

void ui_screenProductDetails_screen_destroy(void)
{
    if(ui_screenProductDetails) lv_obj_del(ui_screenProductDetails);

    // NULL screen variables
    ui_screenProductDetails = NULL;
    ui_Container16 = NULL;
    ui_Image26 = NULL;
    ui_Label67 = NULL;
    ui_Image21 = NULL;
    ui_Label65 = NULL;
    ui_LabelWIS = NULL;
    ui_ImgButton17 = NULL;

}
