// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_ScreenFindAGrocery = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_ImgButton12 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_btnTypeSearch = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Label56 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_btnVoiceSearch = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Label57 = NULL;
lv_obj_t * ui_Label58 = NULL;
// event funtions
void ui_event_ImgButton12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

void ui_event_btnTypeSearch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenFindBook, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenFindBook_screen_init);
    }
}

void ui_event_btnVoiceSearch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenFindVoice, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenFindVoice_screen_init);
    }
}

// build funtions

void ui_ScreenFindAGrocery_screen_init(void)
{
    ui_ScreenFindAGrocery = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenFindAGrocery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenFindAGrocery, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenFindAGrocery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenFindAGrocery, lv_color_hex(0x3DB0E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenFindAGrocery, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_ScreenFindAGrocery);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 312);
    lv_obj_set_height(ui_Container9, 50);
    lv_obj_set_x(ui_Container9, 0);
    lv_obj_set_y(ui_Container9, -85);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_Container9);
    lv_img_set_src(ui_Image19, &ui_img_find_a_grocery_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image19, -94);
    lv_obj_set_y(ui_Image19, -2);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image19, 200);

    ui_Label52 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, 40);
    lv_obj_set_y(ui_Label52, -2);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "Find A Grocery");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton12 = lv_imgbtn_create(ui_ScreenFindAGrocery);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton12, 30);
    lv_obj_set_height(ui_ImgButton12, 30);
    lv_obj_set_x(ui_ImgButton12, -137);
    lv_obj_set_y(ui_ImgButton12, -86);
    lv_obj_set_align(ui_ImgButton12, LV_ALIGN_CENTER);

    ui_Label16 = lv_label_create(ui_ScreenFindAGrocery);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -5);
    lv_obj_set_y(ui_Label16, -48);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Search your grocery quickly \nthe way you like!");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x001100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTypeSearch = lv_btn_create(ui_ScreenFindAGrocery);
    lv_obj_set_width(ui_btnTypeSearch, 128);
    lv_obj_set_height(ui_btnTypeSearch, 128);
    lv_obj_set_x(ui_btnTypeSearch, -74);
    lv_obj_set_y(ui_btnTypeSearch, 41);
    lv_obj_set_align(ui_btnTypeSearch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTypeSearch, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTypeSearch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnTypeSearch, lv_color_hex(0xCACCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTypeSearch, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnTypeSearch, lv_color_hex(0x000E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnTypeSearch, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnTypeSearch, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnTypeSearch, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnTypeSearch, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnTypeSearch, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnTypeSearch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnTypeSearch, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnTypeSearch, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_btnTypeSearch);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 3);
    lv_obj_set_width(ui_Container1, lv_pct(82));
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 19);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x000229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_img_create(ui_btnTypeSearch);
    lv_img_set_src(ui_Image15, &ui_img_typesearch_png);
    lv_obj_set_width(ui_Image15, 62);
    lv_obj_set_height(ui_Image15, 48);
    lv_obj_set_x(ui_Image15, 0);
    lv_obj_set_y(ui_Image15, -27);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label56 = lv_label_create(ui_btnTypeSearch);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 0);
    lv_obj_set_y(ui_Label56, 5);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "Type Search");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_btnTypeSearch);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, -1);
    lv_obj_set_y(ui_Label55, 38);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "Type a name of \nthe grocery item");
    lv_obj_set_style_text_align(ui_Label55, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnVoiceSearch = lv_btn_create(ui_ScreenFindAGrocery);
    lv_obj_set_width(ui_btnVoiceSearch, 128);
    lv_obj_set_height(ui_btnVoiceSearch, 128);
    lv_obj_set_x(ui_btnVoiceSearch, 74);
    lv_obj_set_y(ui_btnVoiceSearch, 41);
    lv_obj_set_align(ui_btnVoiceSearch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnVoiceSearch, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnVoiceSearch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnVoiceSearch, lv_color_hex(0xCACCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnVoiceSearch, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnVoiceSearch, lv_color_hex(0x000E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnVoiceSearch, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnVoiceSearch, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnVoiceSearch, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnVoiceSearch, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnVoiceSearch, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnVoiceSearch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnVoiceSearch, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnVoiceSearch, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_btnVoiceSearch);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_height(ui_Container11, 3);
    lv_obj_set_width(ui_Container11, lv_pct(82));
    lv_obj_set_x(ui_Container11, 0);
    lv_obj_set_y(ui_Container11, 19);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container11, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0x000229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_img_create(ui_btnVoiceSearch);
    lv_img_set_src(ui_Image20, &ui_img_voicesearch_png);
    lv_obj_set_width(ui_Image20, 62);
    lv_obj_set_height(ui_Image20, 48);
    lv_obj_set_x(ui_Image20, 0);
    lv_obj_set_y(ui_Image20, -27);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label57 = lv_label_create(ui_btnVoiceSearch);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, 0);
    lv_obj_set_y(ui_Label57, 5);
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "Voice Search");
    lv_obj_set_style_text_color(ui_Label57, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label57, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_btnVoiceSearch);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, -1);
    lv_obj_set_y(ui_Label58, 38);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "Tap And Speak\nWhat You Need");
    lv_obj_set_style_text_align(ui_Label58, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton12, ui_event_ImgButton12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTypeSearch, ui_event_btnTypeSearch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnVoiceSearch, ui_event_btnVoiceSearch, LV_EVENT_ALL, NULL);

}

void ui_ScreenFindAGrocery_screen_destroy(void)
{
    if(ui_ScreenFindAGrocery) lv_obj_del(ui_ScreenFindAGrocery);

    // NULL screen variables
    ui_ScreenFindAGrocery = NULL;
    ui_Container9 = NULL;
    ui_Image19 = NULL;
    ui_Label52 = NULL;
    ui_ImgButton12 = NULL;
    ui_Label16 = NULL;
    ui_btnTypeSearch = NULL;
    ui_Container1 = NULL;
    ui_Image15 = NULL;
    ui_Label56 = NULL;
    ui_Label55 = NULL;
    ui_btnVoiceSearch = NULL;
    ui_Container11 = NULL;
    ui_Image20 = NULL;
    ui_Label57 = NULL;
    ui_Label58 = NULL;

}
