// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENRETURNSUCCESS_H
#define UI_SCREENRETURNSUCCESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenReturnSuccess
extern void ui_screenReturnSuccess_screen_init(void);
extern void ui_screenReturnSuccess_screen_destroy(void);
extern lv_obj_t * ui_screenReturnSuccess;
extern void ui_event_btnReturnDone(lv_event_t * e);
extern lv_obj_t * ui_btnReturnDone;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

