// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_ScreenFindVoice = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Label60 = NULL;
lv_obj_t * ui_ImgButton13 = NULL;
// event funtions
void ui_event_ImgButton13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenFindAGrocery, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenFindAGrocery_screen_init);
    }
}

// build funtions

void ui_ScreenFindVoice_screen_init(void)
{
    ui_ScreenFindVoice = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenFindVoice, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenFindVoice, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenFindVoice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenFindVoice, lv_color_hex(0x3DB0E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenFindVoice, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_ScreenFindVoice);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 317);
    lv_obj_set_height(ui_Container13, 50);
    lv_obj_set_x(ui_Container13, 5);
    lv_obj_set_y(ui_Container13, -85);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Image22, &ui_img_find_book_icon_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image22, -81);
    lv_obj_set_y(ui_Image22, 0);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label60 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, 36);
    lv_obj_set_y(ui_Label60, 0);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "Find Book");
    lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton13 = lv_imgbtn_create(ui_ScreenFindVoice);
    lv_imgbtn_set_src(ui_ImgButton13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton13, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton13, 30);
    lv_obj_set_height(ui_ImgButton13, 30);
    lv_obj_set_x(ui_ImgButton13, -134);
    lv_obj_set_y(ui_ImgButton13, -85);
    lv_obj_set_align(ui_ImgButton13, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton13, ui_event_ImgButton13, LV_EVENT_ALL, NULL);

}

void ui_ScreenFindVoice_screen_destroy(void)
{
    if(ui_ScreenFindVoice) lv_obj_del(ui_ScreenFindVoice);

    // NULL screen variables
    ui_ScreenFindVoice = NULL;
    ui_Container13 = NULL;
    ui_Image22 = NULL;
    ui_Label60 = NULL;
    ui_ImgButton13 = NULL;

}
