// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#include "../ui.h"

lv_obj_t * ui_screenCreateBill = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_Label69 = NULL;
lv_obj_t * ui_ImgButton15 = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_btnBillContinue = NULL;
lv_obj_t * ui_Label70 = NULL;
lv_obj_t * ui_btnBackCI2 = NULL;
lv_obj_t * ui_Label71 = NULL;
lv_obj_t * ui_Label68 = NULL;
lv_obj_t * ui_LabelCBProducts = NULL;
// event funtions
void ui_event_ImgButton15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenHome, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_screenHome_screen_init);
    }
}

void ui_event_btnBillContinue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenBillCreatedSuccess, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0,
                          &ui_ScreenBillCreatedSuccess_screen_init);
    }
}

void ui_event_btnBackCI2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenIssueEnrollment, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_screenIssueEnrollment_screen_init);
    }
}

// build funtions

void ui_screenCreateBill_screen_init(void)
{
    ui_screenCreateBill = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenCreateBill, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenCreateBill, lv_color_hex(0xA5B4FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenCreateBill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenCreateBill, lv_color_hex(0x6366F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenCreateBill, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container17 = lv_obj_create(ui_screenCreateBill);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 312);
    lv_obj_set_height(ui_Container17, 50);
    lv_obj_set_x(ui_Container17, 0);
    lv_obj_set_y(ui_Container17, -85);
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image28 = lv_img_create(ui_Container17);
    lv_img_set_src(ui_Image28, &ui_img_makeorder_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image28, -77);
    lv_obj_set_y(ui_Image28, 0);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label69 = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, 36);
    lv_obj_set_y(ui_Label69, 0);
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label69, "Create Bill");
    lv_obj_set_style_text_color(ui_Label69, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label69, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label69, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton15 = lv_imgbtn_create(ui_screenCreateBill);
    lv_imgbtn_set_src(ui_ImgButton15, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backbtn_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton15, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_backpressed_png, NULL);
    lv_obj_set_width(ui_ImgButton15, 30);
    lv_obj_set_height(ui_ImgButton15, 30);
    lv_obj_set_x(ui_ImgButton15, -134);
    lv_obj_set_y(ui_ImgButton15, -85);
    lv_obj_set_align(ui_ImgButton15, LV_ALIGN_CENTER);

    ui_Container12 = lv_obj_create(ui_screenCreateBill);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 314);
    lv_obj_set_height(ui_Container12, 50);
    lv_obj_set_x(ui_Container12, 0);
    lv_obj_set_y(ui_Container12, 90);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnBillContinue = lv_btn_create(ui_Container12);
    lv_obj_set_height(ui_btnBillContinue, 32);
    lv_obj_set_width(ui_btnBillContinue, lv_pct(40));
    lv_obj_set_y(ui_btnBillContinue, 0);
    lv_obj_set_x(ui_btnBillContinue, lv_pct(25));
    lv_obj_set_align(ui_btnBillContinue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBillContinue, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBillContinue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBillContinue, lv_color_hex(0x2C30DF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBillContinue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnBillContinue, lv_color_hex(0x18187F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnBillContinue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnBillContinue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnBillContinue, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBillContinue, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBillContinue, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnBillContinue, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnBillContinue, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnBillContinue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnBillContinue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label70 = lv_label_create(ui_btnBillContinue);
    lv_obj_set_width(ui_Label70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label70, "Continue");
    lv_obj_set_style_text_color(ui_Label70, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label70, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackCI2 = lv_btn_create(ui_Container12);
    lv_obj_set_height(ui_btnBackCI2, 32);
    lv_obj_set_width(ui_btnBackCI2, lv_pct(40));
    lv_obj_set_y(ui_btnBackCI2, 0);
    lv_obj_set_x(ui_btnBackCI2, lv_pct(-25));
    lv_obj_set_align(ui_btnBackCI2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBackCI2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBackCI2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackCI2, lv_color_hex(0x6265EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackCI2, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnBackCI2, lv_color_hex(0x8D8DBB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnBackCI2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnBackCI2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnBackCI2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackCI2, lv_color_hex(0x000269), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackCI2, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnBackCI2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnBackCI2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_btnBackCI2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_btnBackCI2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label71 = lv_label_create(ui_btnBackCI2);
    lv_obj_set_width(ui_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label71, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label71, "Back");
    lv_obj_set_style_text_color(ui_Label71, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label71, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label71, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_screenCreateBill);
    lv_obj_set_width(ui_Label68, lv_pct(90));
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label68, -43);
    lv_obj_set_x(ui_Label68, lv_pct(0));
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "Product Name    |    Quantity     |     Price");

    ui_LabelCBProducts = lv_label_create(ui_screenCreateBill);
    lv_obj_set_width(ui_LabelCBProducts, lv_pct(90));
    lv_obj_set_height(ui_LabelCBProducts, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelCBProducts, -24);
    lv_obj_set_x(ui_LabelCBProducts, lv_pct(0));
    lv_obj_set_align(ui_LabelCBProducts, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCBProducts, "");

    lv_obj_add_event_cb(ui_ImgButton15, ui_event_ImgButton15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBillContinue, ui_event_btnBillContinue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBackCI2, ui_event_btnBackCI2, LV_EVENT_ALL, NULL);

}

void ui_screenCreateBill_screen_destroy(void)
{
    if(ui_screenCreateBill) lv_obj_del(ui_screenCreateBill);

    // NULL screen variables
    ui_screenCreateBill = NULL;
    ui_Container17 = NULL;
    ui_Image28 = NULL;
    ui_Label69 = NULL;
    ui_ImgButton15 = NULL;
    ui_Container12 = NULL;
    ui_btnBillContinue = NULL;
    ui_Label70 = NULL;
    ui_btnBackCI2 = NULL;
    ui_Label71 = NULL;
    ui_Label68 = NULL;
    ui_LabelCBProducts = NULL;

}
