// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENFINDBOOK_H
#define UI_SCREENFINDBOOK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenFindBook
extern void ui_screenFindBook_screen_init(void);
extern void ui_screenFindBook_screen_destroy(void);
extern lv_obj_t * ui_screenFindBook;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label9;
extern void ui_event_ImgButton13(lv_event_t * e);
extern lv_obj_t * ui_ImgButton13;
extern lv_obj_t * ui_taFBookName;
extern void ui_event_btnSearchBook(lv_event_t * e);
extern lv_obj_t * ui_btnSearchBook;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_ErrorFBEBN;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

