// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: FindMyGrocery

#ifndef UI_SCREENFINDBOOKINFO_H
#define UI_SCREENFINDBOOKINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenFindBookInfo
extern void ui_screenFindBookInfo_screen_init(void);
extern void ui_screenFindBookInfo_screen_destroy(void);
extern void ui_event_screenFindBookInfo(lv_event_t * e);
extern lv_obj_t * ui_screenFindBookInfo;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_labelBDBookName;
extern lv_obj_t * ui_labelBDStatus;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_labelBDBookCode;
extern lv_obj_t * ui_labelBDLocation;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_btnBlinkRack;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_btnBlinkBook;
extern lv_obj_t * ui_Label13;
extern void ui_event_btnShowBookLocation(lv_event_t * e);
extern lv_obj_t * ui_btnShowBookLocation;
extern lv_obj_t * ui_Label28;
extern void ui_event_btnOpenOnPhone(lv_event_t * e);
extern lv_obj_t * ui_btnOpenOnPhone;
extern lv_obj_t * ui_Label15;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_MapFullContainer;
extern lv_obj_t * ui_imgMapLocationcont;
extern lv_obj_t * ui_imgMapLocation;
extern void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_QrFullContainer;
extern lv_obj_t * ui_imgQrCode;
extern lv_obj_t * ui_imgQR;
extern lv_obj_t * ui_Label17;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button7;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

